Repository zanata/zanata-platform, pull requests merged in 2018-04, with the labels that each got.

#730 feat(ZNTA-2409): Frontend Internationalization Workflow
  server/zanata-frontend/pom.xml
  server/zanata-frontend/src/.gitignore
  server/zanata-frontend/src/app/editor/containers/TranslationInfoPanel/index.js
  server/zanata-frontend/src/app/editor/index.html
  server/zanata-frontend/src/app/editor/messages/en-us.json
  server/zanata-frontend/src/app/editor/messages/index.js
  server/zanata-frontend/src/messages/en-us.json
  server/zanata-frontend/src/messages/en.json
  server/zanata-frontend/src/messages/ja.json
  server/zanata-frontend/src/package.json
  server/zanata-frontend/src/scripts/build.js
  server/zanata-frontend/src/scripts/extract-messages.js
  server/zanata-frontend/src/webpack.config.js
  server/zanata-frontend/src/yarn.lock
  server/zanata-frontend/zanata.xml
Labels: Reviewed, Verified

#766 Update TypeScript to 2.8.1
  server/zanata-frontend/src/package.json
  server/zanata-frontend/src/yarn.lock
Labels: Ignore CodeCov, No QA (1st vote), No QA (2nd vote), Reviewed

#767 Add newer dependency vulnerability scanners
  Jenkinsfile
  parent/pom.xml
  server/pom.xml
Labels: No QA (1st vote), No QA (2nd vote), Reviewed

#777 Disable maven-security-versions
  parent/pom.xml
Labels: No QA (1st vote), No QA (2nd vote), Reviewed

#779 Upgrade commons-fileupload
  server/pom.xml
  server/services/pom.xml
  server/zanata-war/pom.xml
Labels: No QA (1st vote), No QA (2nd vote), Reviewed

#769 fix(ZNTA-2473) background colour of editor sidebar panels
  server/zanata-frontend/src/app/editor/containers/Sidebar/index.css
Labels: Reviewed, Verified

#765 refactor(ZNTA-2400): Consistency of sizes in css (use rem)
  server/zanata-frontend/src/app/components/Sidebar/index.less
  server/zanata-frontend/src/app/containers/Admin/index.less
  server/zanata-frontend/src/app/containers/Explore/index.less
  server/zanata-frontend/src/app/containers/Glossary/index.less
  server/zanata-frontend/src/app/containers/ProjectVersion/index.less
  server/zanata-frontend/src/app/editor/components/Dropdown/index.css
  server/zanata-frontend/src/app/editor/components/EditorSearchInput/index.css
  server/zanata-frontend/src/app/editor/components/GlossaryTermModal/index.css
  server/zanata-frontend/src/app/editor/components/TransUnit/index.css
  server/zanata-frontend/src/app/editor/containers/Root/index.css
  server/zanata-frontend/src/app/editor/containers/Sidebar/index.css
  server/zanata-frontend/src/app/editor/containers/SuggestionDetailsModal/index.css
  server/zanata-frontend/src/app/styles/legacy.less
  server/zanata-frontend/src/app/styles/style.less
Labels: Ignore CodeCov, Reviewed, Verified

#781 Update jsch
  client/zanata-maven-plugin/pom.xml
Labels: No QA (1st vote), No QA (2nd vote)

#773 refactor(ZNTA-2465): ant-design static buttons
  server/zanata-frontend/src/.stylelintrc
  server/zanata-frontend/src/app/components/DraggableVersionPanels/DraggableVersionPanels.test.js
  server/zanata-frontend/src/app/components/DraggableVersionPanels/index.tsx
  server/zanata-frontend/src/app/components/Notification/component.js
  server/zanata-frontend/src/app/containers/Admin/Review.js
  server/zanata-frontend/src/app/containers/Admin/index.less
  server/zanata-frontend/src/app/containers/Explore/TeaserListHeader.jsx
  server/zanata-frontend/src/app/containers/Explore/index.js
  server/zanata-frontend/src/app/containers/Explore/index.less
  server/zanata-frontend/src/app/containers/Glossary/index.js
  server/zanata-frontend/src/app/containers/Glossary/index.less
  server/zanata-frontend/src/app/containers/Languages/index.js
  server/zanata-frontend/src/app/containers/Languages/index.less
  server/zanata-frontend/src/app/containers/UserProfile/CalendarMonthMatrix.jsx
  server/zanata-frontend/src/app/containers/UserProfile/RecentContributions.jsx
  server/zanata-frontend/src/app/entrypoint/index.js
  server/zanata-frontend/src/app/styles/ant-theme-vars.less
  server/zanata-frontend/src/app/styles/antd.less
  server/zanata-frontend/src/app/styles/style.less
  server/zanata-frontend/src/package.json
  server/zanata-frontend/src/webpack.config.js
  server/zanata-frontend/src/yarn.lock
Labels: Ignore CodeCov, Reviewed, Verified

#787 Reformat 0install docs
  docs/client/installation/linux-installation.md
Labels: No QA (1st vote), No QA (2nd vote)

#788 fix: storybook frontend/editor builds
  server/zanata-frontend/src/webpack.config.js
Labels: No QA (1st vote), No QA (2nd vote)

#789 fix(ZNTA-2491) add status utility classes to frontend
  server/zanata-frontend/src/app/styles/ant-theme-vars.less
Labels: No QA (1st vote), No QA (2nd vote), Reviewed

#785 style: dynamically size editor sidebar
  server/zanata-frontend/src/app/editor/containers/Sidebar/index.css
  server/zanata-frontend/src/app/editor/containers/Sidebar/index.js
Labels: Ignore CodeCov, Reviewed, Verified

#782 fix(ZNTA-2490): Fix missing profile email icon
  server/zanata-frontend/src/app/containers/UserProfile/index.jsx
Labels: Ignore CodeCov, Reviewed, Verified

#761 Use configure-app-server.js for rundev.sh
  server/docker/Dockerfile
  server/docker/conf/zanata-config.cli
  server/docker/docker-compose.yml
  server/docker/rundev.sh
  server/etc/scripts/allocate-jboss-ports
  server/etc/scripts/configure-app-server.js
  server/etc/scripts/configureAppServer.js
  server/etc/scripts/jboss-cli-jjs
  server/etc/scripts/runJbossCli.groovy
  server/etc/scripts/tsconfig.json
  server/etc/scripts/types.d.ts
  server/functional-test/pom.xml
Labels: Reviewed, Verified

#793 fix: use tsImportPlugin to load ant.design in webpack build
  server/zanata-frontend/src/package.json
  server/zanata-frontend/src/webpack.config.js
  server/zanata-frontend/src/yarn.lock
Labels: Reviewed

#791 fix(ZNTA-2497) support OpenID-only option
  server/services/src/main/java/org/zanata/ApplicationConfiguration.java
  server/services/src/main/java/org/zanata/ZanataInit.java
  server/services/src/main/java/org/zanata/action/LoginAction.java
Labels: Ignore CodeCov, Reviewed, Verified

#792 Backport new vulnerability scanners (#767 and #777)
  Jenkinsfile
  parent/pom.xml
  server/pom.xml
Labels: No QA (1st vote), No QA (2nd vote), Reviewed

#796 update: jackson-databind library
  server/pom.xml
Labels: Ignore CodeCov, No QA (1st vote), No QA (2nd vote)

#784 refactor(ZNTA-2460): split legacy.less into frontend-nav and frontend-jsf
  server/zanata-frontend/src/app/containers/App.js
  server/zanata-frontend/src/app/styles/frontend-jsf.less
  server/zanata-frontend/src/app/styles/frontend-nav.less
  server/zanata-frontend/src/app/styles/legacy.less
Labels: Ignore CodeCov, Reviewed, Verified

#783 style(ZNTA-2488) add Tachyons css utility classes to frontend
  server/zanata-frontend/src/app/entrypoint/index.js
  server/zanata-frontend/src/package.json
  server/zanata-frontend/src/yarn.lock
Labels: Ignore CodeCov, Reviewed, Verified

#802 Add aether-api
  parent/pom.xml
Labels: No QA (1st vote), No QA (2nd vote), Release, Reviewed

#800 feat: delete version group
  server/services/src/main/java/org/zanata/action/VersionGroupHome.java
  server/services/src/main/resources/messages.properties
  server/zanata-war/src/main/webapp/WEB-INF/layout/version-group/delete_group_confirmation_modal.xhtml
  server/zanata-war/src/main/webapp/WEB-INF/layout/version-group/settings-tab.xhtml
Labels: Ignore CodeCov, Reviewed, Verified
