Repository zanata/zanata-platform, pull requests merged in 2018-02, with the labels that each got.

#708 Run watch tasks on separate ports
  server/docker/conf/zanata-config.cli
  server/zanata-frontend/src/.eslintrc
  server/zanata-frontend/src/README.md
  server/zanata-frontend/src/scripts/dev-server.config.js
  server/zanata-frontend/src/scripts/dev-server.js
  server/zanata-frontend/src/webpack.config.js
Labels: No QA (1st vote), No QA (2nd vote), Reviewed

#718 fix: invalid js import syntax
  server/zanata-frontend/src/app/editor/api/index.js
Labels: Reviewed, Verified

#688 feat(ZNTA-2318): Editor Review / Reject Translation
  server/services/src/main/java/org/zanata/rest/editor/dto/ReviewData.java
  server/services/src/main/java/org/zanata/rest/editor/service/TranslationReviewService.java
  server/services/src/main/java/org/zanata/rest/editor/service/resource/TranslationReviewResource.java
  server/services/src/main/java/org/zanata/webtrans/server/rpc/AddReviewCommentHandler.java
  server/services/src/test/java/org/zanata/rest/editor/dto/ReviewDataTest.java
  server/services/src/test/java/org/zanata/rest/editor/service/TranslationReviewServiceTest.java
  server/zanata-frontend/src/app/editor/actions/key-shortcuts-actions.js
  server/zanata-frontend/src/app/editor/actions/review-trans-actions.js
  server/zanata-frontend/src/app/editor/actions/review-trans-actions.test.js
  server/zanata-frontend/src/app/editor/api/index.js
  server/zanata-frontend/src/app/editor/app.css
  server/zanata-frontend/src/app/editor/components/Dropdown/index.css
  server/zanata-frontend/src/app/editor/components/TransUnit/index.js
  server/zanata-frontend/src/app/editor/components/TransUnitTranslationFooter.js
  server/zanata-frontend/src/app/editor/components/TransUnitTranslationPanel.js
  server/zanata-frontend/src/app/editor/containers/MainContent.js
  server/zanata-frontend/src/app/editor/containers/RejectTranslationModal/CriteriaDropdown.js
  server/zanata-frontend/src/app/editor/containers/RejectTranslationModal/CriteriaDropdown.test.js
  server/zanata-frontend/src/app/editor/containers/RejectTranslationModal/PriorityDropdown.js
  server/zanata-frontend/src/app/editor/containers/RejectTranslationModal/PriorityDropdown.test.js
  server/zanata-frontend/src/app/editor/containers/RejectTranslationModal/RejectTranslationModal.story.js
  server/zanata-frontend/src/app/editor/containers/RejectTranslationModal/index.css
  server/zanata-frontend/src/app/editor/containers/RejectTranslationModal/index.js
  server/zanata-frontend/src/app/editor/containers/Root/index.js
  server/zanata-frontend/src/app/editor/reducers/index.js
  server/zanata-frontend/src/app/editor/reducers/review-trans-reducer.js
  server/zanata-frontend/src/app/editor/reducers/review-trans-reducer.test.js
  server/zanata-frontend/src/app/editor/utils/reject-trans-util.js
  server/zanata-frontend/src/app/editor/utils/status-util.js
  server/zanata-frontend/src/app/reducers/admin-reducer.js
  server/zanata-frontend/src/app/reducers/admin-reducer.test.js
  server/zanata-frontend/src/app/reducers/common-reducer.js
  server/zanata-frontend/src/app/reducers/glossary-reducer.js
  server/zanata-frontend/src/app/reducers/languages-reducer.js
  server/zanata-frontend/src/app/reducers/profile-reducer.js
Labels: Reviewed, Verified

#678 Move entry points, require all source files as test
  server/zanata-frontend/src/app/editor/entrypoint/index.js
  server/zanata-frontend/src/app/entrypoint/index.js
  server/zanata-frontend/src/app/entrypoint/legacy.js
  server/zanata-frontend/src/app/require-all.test.js
  server/zanata-frontend/src/package.json
  server/zanata-frontend/src/webpack.config.js
  server/zanata-frontend/src/yarn.lock
Labels: Ignore CodeCov, Reviewed, Verified

#685 test(unittest): ActivateAction test
  server/services/src/main/java/org/zanata/action/ActivateAction.java
  server/services/src/test/java/org/zanata/action/ActivateActionTest.java
Labels: No QA (1st vote), No QA (2nd vote), Reviewed

#692 test(unittest): AdapterUtils unit test
  server/services/src/test/java/org/zanata/adapter/AdapterUtilsTest.java
Labels: No QA (1st vote), No QA (2nd vote), Reviewed

#726 Update Kotlin to 1.2.21
  server/pom.xml
Labels: No QA (1st vote), No QA (2nd vote), Reviewed

#727 Update versions-maven-plugin; ignore prereleases
  build-tools/src/main/resources/zanata-build-tools/versions-rules.xml
  parent/pom.xml
Labels: No QA (1st vote), No QA (2nd vote), Reviewed

#728 Revert "Update Kotlin to 1.2.21"
  server/pom.xml
Labels: No QA (1st vote), No QA (2nd vote)

#722 Add nexus-staging-maven-plugin in release profile
  parent/pom.xml
Labels: Ignore CodeCov, No QA (1st vote), No QA (2nd vote), Reviewed

#721 fix(ZNTA-2395): references to http
  server/zanata-frontend/src/.storybook-editor/__snapshots__/storyshots-editor.test.js.snap
  server/zanata-frontend/src/app/editor/components/ActivityFeedItem/ActivityFeedItem.story.js
  server/zanata-frontend/src/app/editor/components/DashboardLink/DashboardLink.test.js
  server/zanata-frontend/src/app/editor/components/DashboardLink/index.js
  server/zanata-frontend/src/app/editor/index.html
  server/zanata-frontend/src/app/editor/reducers/header-data-reducer.js
  server/zanata-frontend/src/app/editor/reducers/header-data-reducer.test.js
  server/zanata-frontend/src/index.html
Labels: Reviewed, Verified

#724 feat(ZNTA-2392): React Editor rejection modal - enforce criteria comment required option
  server/gwt-shared/src/main/java/org/zanata/webtrans/shared/rest/dto/TransReviewCriteria.java
  server/services/src/main/java/org/zanata/rest/review/ReviewService.java
  server/services/src/main/resources/db/changelogs/db.changelog-4.5.xml
  server/services/src/main/resources/db/db.changelog.xml
  server/zanata-frontend/src/.storybook-frontend/__snapshots__/storyshots-frontend.test.js.snap
  server/zanata-frontend/src/app/actions/review-actions.js
  server/zanata-frontend/src/app/components/RejectionsForm/RejectionsForm.story.js
  server/zanata-frontend/src/app/components/RejectionsForm/index.js
  server/zanata-frontend/src/app/containers/Admin/Review.js
  server/zanata-frontend/src/app/editor/components/TransUnit/index.js
  server/zanata-frontend/src/app/editor/containers/MainContent.js
  server/zanata-frontend/src/app/editor/containers/RejectTranslationModal/CriteriaDropdown.js
  server/zanata-frontend/src/app/editor/containers/RejectTranslationModal/CriteriaDropdown.test.js
  server/zanata-frontend/src/app/editor/containers/RejectTranslationModal/RejectTranslationModal.story.js
  server/zanata-frontend/src/app/editor/containers/RejectTranslationModal/index.css
  server/zanata-frontend/src/app/editor/containers/RejectTranslationModal/index.js
  server/zanata-frontend/src/app/editor/reducers/review-trans-reducer.js
  server/zanata-frontend/src/app/editor/reducers/review-trans-reducer.test.js
  server/zanata-frontend/src/app/editor/utils/reject-trans-util.ts
  server/zanata-frontend/src/app/reducers/admin-reducer.test.js
  server/zanata-model/src/main/java/org/zanata/model/ReviewCriteria.java
Labels: Reviewed, Verified

#723 ZNTA-2391: admin react page
  server/services/src/main/java/org/zanata/servlet/UrlRewriteConfig.java
  server/zanata-frontend/src/app/containers/Admin/index.js
  server/zanata-frontend/src/app/containers/Admin/index.less
  server/zanata-frontend/src/app/containers/Root.js
  server/zanata-frontend/src/app/styles/style.less
  server/zanata-frontend/src/app/styles/variables.less
  server/zanata-war/src/main/webapp/WEB-INF/faces-config.xml
  server/zanata-war/src/main/webapp/admin/create_user.xhtml
  server/zanata-war/src/main/webapp/admin/processmanager.xhtml
  server/zanata-war/src/main/webapp/admin/roledetail.xhtml
  server/zanata-war/src/main/webapp/admin/rolemanager.xhtml
  server/zanata-war/src/main/webapp/admin/roleruledetails.xhtml
  server/zanata-war/src/main/webapp/admin/rolerules.xhtml
  server/zanata-war/src/main/webapp/admin/search.xhtml
  server/zanata-war/src/main/webapp/admin/server_configuration.xhtml
  server/zanata-war/src/main/webapp/admin/stats.xhtml
  server/zanata-war/src/main/webapp/admin/userdetail.xhtml
  server/zanata-war/src/main/webapp/admin/usermanager.xhtml
  server/zanata-war/src/main/webapp/tm/create.xhtml
  server/zanata-war/src/main/webapp/tm/home.xhtml
Labels: Reviewed, Verified

#725 fix(ZNTA-2394) preconnect and preload working with react pages
  server/gwt-editor/src/main/webapp/webtrans/Application.xhtml
  server/services/src/test/java/org/zanata/webtrans/public/images/fontello/css/fontello.css
  server/zanata-war/src/main/webapp/WEB-INF/template/template.xhtml
  server/zanata-war/src/main/webapp/WEB-INF/template/template_nobanner.xhtml
  server/zanata-war/src/main/webapp/a/index.xhtml
  server/zanata-war/src/main/webapp/editor/index.xhtml
  server/zanata-war/src/main/webapp/resources/assets/css/style.css
  server/zanata-war/src/main/webapp/resources/fontello/css/fontello.css
Labels: Reviewed, Verified

#672 fix(ZNTA-2313): update admin rejection panel
  server/zanata-frontend/src/.storybook-editor/__snapshots__/storyshots-editor.test.js.snap
  server/zanata-frontend/src/.storybook-frontend/__snapshots__/storyshots-frontend.test.js.snap
  server/zanata-frontend/src/app/components/RejectionsForm/RejectionsForm.story.js
  server/zanata-frontend/src/app/components/RejectionsForm/index.js
  server/zanata-frontend/src/app/components/RejectionsForm/index.less
  server/zanata-frontend/src/app/containers/Admin/Review.js
  server/zanata-frontend/src/app/editor/components/RejectTranslationModal/RejectTranslationModal.story.js
  server/zanata-frontend/src/app/editor/components/RejectTranslationModal/RejectTranslationModalNoCrit.js
  server/zanata-frontend/src/app/editor/components/RejectTranslationModal/index.js
Labels: Reviewed, Verified

#734 fix(ZNTA-2408) set RejectTranslationModal Criteria dropdown to have empty field by default
  server/gwt-editor/src/main/java/org/zanata/webtrans/client/view/ForceReviewCommentWidget.java
  server/zanata-frontend/src/.storybook-editor/__snapshots__/storyshots-editor.test.js.snap
  server/zanata-frontend/src/app/editor/components/RejectTranslationModal/RejectTranslationModal.story.js
  server/zanata-frontend/src/app/editor/components/RejectTranslationModal/index.js
  server/zanata-frontend/src/app/editor/containers/RejectTranslationModal/CriteriaDropdown.js
  server/zanata-frontend/src/app/editor/containers/RejectTranslationModal/CriteriaDropdown.test.js
  server/zanata-frontend/src/app/editor/containers/RejectTranslationModal/PriorityDropdown.js
  server/zanata-frontend/src/app/editor/containers/RejectTranslationModal/PriorityDropdown.test.js
  server/zanata-frontend/src/app/editor/containers/RejectTranslationModal/index.css
  server/zanata-frontend/src/app/editor/containers/RejectTranslationModal/index.js
Labels: Reviewed, Verified

#736 refactor(ZNTA-2393) translation split dropdown buttons in editor
  server/zanata-frontend/src/app/editor/components/SplitDropdown/index.js
Labels: Reviewed, Verified

#732 fix(ZNTA-2399) increase visibility of panel resizers in editors
  server/zanata-frontend/src/app/editor/css/resizer/index.css
  server/zanata-war/src/main/webapp/resources/assets/css/application.css
Labels: Ignore CodeCov, Reviewed, Verified

#693 Use CurrentUser to get authenticated HAccount
  server/functional-test/src/main/java/org/zanata/workflow/LoginWorkFlow.java
  server/services/src/main/java/org/zanata/action/AbstractProfileAction.java
  server/services/src/main/java/org/zanata/action/AccountMergeAction.java
  server/services/src/main/java/org/zanata/action/ProfileAction.java
  server/services/src/main/java/org/zanata/action/ProjectHome.java
  server/services/src/main/java/org/zanata/action/ProjectHomeAction.java
  server/services/src/main/java/org/zanata/dao/ProjectDAO.java
  server/services/src/main/java/org/zanata/rest/editor/service/UserService.java
  server/services/src/main/java/org/zanata/seam/security/CurrentUser.java
  server/services/src/main/java/org/zanata/seam/security/CurrentUserImpl.java
  server/services/src/main/java/org/zanata/security/SecurityFunctions.java
  server/services/src/test/java/org/zanata/action/AccountMergeActionTest.java
  server/services/src/test/java/org/zanata/action/NewProfileActionTest.java
  server/services/src/test/java/org/zanata/dao/ProjectDAOTest.java
  server/services/src/test/java/org/zanata/dao/TextFlowStreamingDAOTest.java
  server/services/src/test/java/org/zanata/rest/editor/service/UserServiceTest.java
  server/services/src/test/java/org/zanata/rest/service/FileServiceTest.java
  server/services/src/test/java/org/zanata/rest/service/LocalesServiceTest.java
  server/services/src/test/java/org/zanata/rest/service/ProjectVersionTest.java
  server/services/src/test/java/org/zanata/rest/service/ProjectsServiceTest.java
  server/services/src/test/java/org/zanata/rest/service/StatisticsServiceImplTest.java
  server/services/src/test/java/org/zanata/rest/service/raw/AccountRawRestITCase.java
  server/services/src/test/java/org/zanata/rest/service/raw/VersionRawRestITCase.kt
  server/services/src/test/java/org/zanata/seam/security/AltCurrentUser.java
  server/services/src/test/java/org/zanata/security/ZanataIdentityTest.java
  server/services/src/test/java/org/zanata/service/impl/CopyTransServiceImplParameterizedTest.java
  server/services/src/test/java/org/zanata/service/impl/CopyTransServiceImplTest.java
  server/services/src/test/java/org/zanata/service/impl/CopyVersionServiceImplPerformanceTest.java
  server/services/src/test/java/org/zanata/service/impl/CopyVersionServiceImplTest.java
  server/services/src/test/java/org/zanata/service/impl/GlossaryFileServiceImplTest.java
  server/services/src/test/java/org/zanata/service/impl/MergeTranslationsServiceImplTest.java
  server/services/src/test/java/org/zanata/service/impl/TransMemoryMergeServiceImplJpaTest.java
  server/services/src/test/java/org/zanata/service/impl/TranslationServiceImplTest.java
  server/services/src/test/java/org/zanata/service/impl/VersionGroupServiceImplTest.java
  server/services/src/test/java/org/zanata/webtrans/server/rpc/GetTransUnitListHandlerTest.java
Labels: Ignore CodeCov, Verified

#735 fix(ZNTA-2410) width of close buttons in GWT now handles text correctly
  server/gwt-editor/src/main/java/org/zanata/webtrans/client/resources/UiMessages.java
  server/gwt-editor/src/main/java/org/zanata/webtrans/client/view/GlossaryDetailsView.java
  server/gwt-editor/src/main/java/org/zanata/webtrans/client/view/GlossaryDetailsView.ui.xml
  server/zanata-frontend/src/app/styles/legacy.less
Labels: Ignore CodeCov, Reviewed, Verified

#719 feat(ZNTA-2380): react editor project review / translate permissions
  server/services/src/main/java/org/zanata/rest/editor/service/UserService.java
  server/services/src/main/java/org/zanata/rest/editor/service/resource/UserResource.java
  server/services/src/test/java/org/zanata/rest/editor/service/UserServiceTest.java
  server/zanata-frontend/src/app/editor/actions/header-action-types.js
  server/zanata-frontend/src/app/editor/actions/header-actions.js
  server/zanata-frontend/src/app/editor/actions/phrases-actions.js
  server/zanata-frontend/src/app/editor/api/api.test.js
  server/zanata-frontend/src/app/editor/api/index.js
  server/zanata-frontend/src/app/editor/components/TransUnitTranslationFooter.js
  server/zanata-frontend/src/app/editor/components/TransUnitTranslationPanel.js
  server/zanata-frontend/src/app/editor/components/TransUnitTranslationPanel.test.js
  server/zanata-frontend/src/app/editor/reducers/header-data-reducer.js
  server/zanata-frontend/src/app/editor/reducers/header-data-reducer.test.js
  server/zanata-frontend/src/app/editor/utils/status-util.js
  server/zanata-frontend/src/app/editor/utils/status-util.test.js
Labels: Reviewed, Verified

#716 fix: add limit to glossary fields
  api/zanata-common-api/src/main/java/org/zanata/rest/dto/GlossaryEntry.java
  api/zanata-common-api/src/main/java/org/zanata/rest/dto/GlossaryTerm.java
  server/services/src/main/java/org/zanata/service/impl/GlossaryFileServiceImpl.java
  server/services/src/main/resources/db/changelogs/db.changelog-4.5.xml
  server/services/src/main/resources/db/db.changelog.xml
  server/services/src/test/java/org/zanata/service/impl/GlossarySearchServiceImplTest.java
  server/zanata-frontend/src/.storybook-frontend/__snapshots__/storyshots-frontend.test.js.snap
  server/zanata-frontend/src/app/components/TextInput/index.js
  server/zanata-frontend/src/app/containers/Glossary/Entry.js
  server/zanata-frontend/src/app/containers/Glossary/EntryModal.js
  server/zanata-frontend/src/app/containers/Glossary/NewEntryModal.js
  server/zanata-model-test/src/main/resources/performance/GlossaryTest.dbunit.xml
  server/zanata-model/src/main/java/org/zanata/model/HGlossaryEntry.java
  server/zanata-model/src/main/java/org/zanata/model/HGlossaryTerm.java
Labels: Reviewed, Verified
