Repository zanata/zanata-platform, pull requests merged in 2018-06, with the labels that each got.

#815 fix(ZNTA-544): include user content in emails as plain text
  server/services/src/main/java/org/zanata/email/ContactAdminAnonymousEmailStrategy.java
  server/services/src/main/java/org/zanata/email/ContactAdminEmailStrategy.java
  server/services/src/main/java/org/zanata/email/ContactLanguageCoordinatorEmailStrategy.java
  server/services/src/main/java/org/zanata/email/ContactLanguageTeamMembersEmailStrategy.java
  server/services/src/main/java/org/zanata/email/DeclineLanguageRequestEmailStrategy.java
  server/services/src/main/java/org/zanata/email/RequestToJoinLanguageEmailStrategy.java
  server/services/src/main/java/org/zanata/email/RequestToJoinVersionGroupEmailStrategy.java
  server/services/src/main/java/org/zanata/util/HtmlUtil.java
  server/services/src/main/resources/org/zanata/email/templates/decline_language_team_request.vm
  server/services/src/main/resources/org/zanata/email/templates/email_admin.vm
  server/services/src/main/resources/org/zanata/email/templates/email_admin_anonymous.vm
  server/services/src/main/resources/org/zanata/email/templates/email_coordinator.vm
  server/services/src/main/resources/org/zanata/email/templates/email_language_team_members.vm
  server/services/src/main/resources/org/zanata/email/templates/email_request_to_join_group.vm
  server/services/src/main/resources/org/zanata/email/templates/email_request_to_join_language.vm
  server/services/src/test/java/org/zanata/email/VelocityEmailStrategyTest.java
  server/services/src/test/java/org/zanata/util/HtmlUtilTest.java
Labels: Release, Reviewed, Verified

#858 fix(ZNTA-1083): add offline PO upload for File projects
  docs/user-guide/documents/upload-documents.md
  server/services/src/main/java/org/zanata/service/impl/TranslationFileServiceImpl.java
  server/services/src/main/resources/messages.properties
  server/services/src/test/java/org/zanata/service/impl/TranslationFileServiceImplTest.java
  server/zanata-war/src/main/webapp/WEB-INF/layout/version/upload_translation_modal.xhtml
Labels: Release, Reviewed, Verified

#864 fix(UI): glossary entry details icon
  server/zanata-frontend/src/app/containers/Glossary/Entry.js
Labels: Ignore CodeCov, Release, Reviewed, Verified

#867 fix(ZNTA-2596): detect invalid project slug in url
  server/services/src/main/java/org/zanata/action/VersionHome.java
Labels: Ignore CodeCov, Release, Verified

#855 Update maven-javadoc-plugin, maven-source-plugin, maven-compiler-plug…
  build-tools/pom.xml
  client/pom.xml
  client/stub-server/pom.xml
  parent/pom.xml
  server/gwt-shared/pom.xml
  server/pom.xml
Labels: Awaiting review, Release

#871 upgrade less-loader to 4.0.5
  server/zanata-frontend/src/package.json
  server/zanata-frontend/src/yarn.lock
Labels: No QA (1st vote), No QA (2nd vote), Release, Reviewed

#873 remove(profile): doclint-java8-disable
  parent/pom.xml
  server/pom.xml
Labels: No QA (1st vote), No QA (2nd vote), Release, Reviewed

#872 fix: improve stats collection
  server/services/src/main/java/org/zanata/dao/ProjectIterationDAO.java
  server/services/src/main/java/org/zanata/rest/service/StatisticsServiceImpl.java
Labels: Reviewed, Verified

#874 fix: remove requireReview flag
  docs/images/version-translation-settings.png
  docs/user-guide/review/review-enable.md
  docs/user-guide/review/translation-review.md
  docs/user-guide/versions/version-settings.md
  mkdocs.yml
  server/services/src/main/java/org/zanata/action/VersionHome.java
  server/services/src/main/java/org/zanata/service/impl/CopyTransServiceImpl.java
  server/services/src/main/java/org/zanata/service/impl/CopyTransWorkFactory.java
  server/services/src/main/resources/db/changelogs/db.changelog-4.6.xml
  server/services/src/main/resources/messages.properties
  server/services/src/test/java/org/zanata/service/impl/CopyTransServiceImplParameterizedTest.java
  server/services/src/test/java/org/zanata/service/impl/CopyTransServiceImplTest.java
  server/services/src/test/java/org/zanata/service/impl/CopyTransServiceUnitTest.java
  server/services/src/test/java/org/zanata/service/impl/CopyTransWorkTest.java
  server/services/src/test/java/org/zanata/service/impl/CopyVersionServiceImplTest.java
  server/zanata-model-test/src/main/resources/performance/GetTransUnitListTest.dbunit.xml
  server/zanata-model/src/main/java/org/zanata/model/HDocument.java
  server/zanata-model/src/main/java/org/zanata/model/HProjectIteration.java
  server/zanata-war/src/main/webapp/WEB-INF/layout/version/settings-tab.xhtml
  server/zanata-war/src/main/webapp/iteration/view.xhtml
Labels: Reviewed, Verified

#861 fix(ZNTA-2590) decrease height of keyboard shortcut modal, add scrolling
  server/zanata-frontend/src/app/editor/containers/KeyShortcutCheatSheet/index.css
Labels: Ignore CodeCov, Release, Reviewed, Verified

#880 Enable strictNullChecks for TypeScript
  server/zanata-frontend/src/app/actions/version-actions.js
  server/zanata-frontend/src/app/components/Icons/Readme.md
  server/zanata-frontend/src/app/containers/Languages/DeleteEntry.js
  server/zanata-frontend/src/app/containers/UserProfile/DayMatrix.jsx
  server/zanata-frontend/src/app/editor/components/RejectTranslationModal/PriorityDropdown.js
  server/zanata-frontend/src/app/editor/components/Suggestion.js
  server/zanata-frontend/src/app/editor/components/TransUnitStatus.tsx
  server/zanata-frontend/src/app/editor/containers/ActivityTab.tsx
  server/zanata-frontend/src/app/editor/containers/TranslationInfoPanel/DetailsPane.tsx
  server/zanata-frontend/src/app/editor/reducers/header-data-reducer.js
  server/zanata-frontend/src/app/editor/reducers/review-trans-reducer.js
  server/zanata-frontend/src/app/editor/reducers/ui-reducer.test.js
  server/zanata-frontend/src/app/editor/utils/phrase-util.ts
  server/zanata-frontend/src/app/editor/utils/status-util.test.js
  server/zanata-frontend/src/app/editor/watchers/phrase-detail.js
  server/zanata-frontend/src/app/editor/watchers/phrase-list.js
  server/zanata-frontend/src/app/reducers/admin-reducer.js
  server/zanata-frontend/src/app/require-all.test.ts
  server/zanata-frontend/src/app/utils/GlossaryHelper.js
  server/zanata-frontend/src/app/utils/StringUtils.test.js
  server/zanata-frontend/src/tsconfig.json
  server/zanata-frontend/src/webpack.config.js
Labels: No QA (1st vote), No QA (2nd vote), Reviewed

#886 fix(ZNTA-2615): alpha editor translate button
  server/zanata-frontend/src/app/editor/components/SplitDropdown/index.js
Labels: Release, Reviewed, Verified

#890 fix: GWT editor option
  server/services/src/main/java/org/zanata/webtrans/server/rpc/LoadOptionsHandler.java
Labels: Release, Reviewed, Verified

#889 fix(ZNTA-2614) increase contrast of concurrent editor username in gwt editor
  server/gwt-editor/src/main/java/org/zanata/webtrans/client/ui/TranslatorListWidget.ui.xml
Labels: Release, Reviewed, Verified

#868 fix(ZNTA-2591) remove extra width and height from languages page + minor styling fixes
  server/zanata-frontend/src/app/containers/Languages/index.js
  server/zanata-frontend/src/app/containers/Languages/index.less
  server/zanata-frontend/src/app/styles/antd.less
  server/zanata-frontend/src/app/styles/style.less
Labels: Release, Reviewed, Verified

#883 fix(ZNTA-2613): hide activity commentbox when no translations to comment on
  server/zanata-frontend/src/app/editor/containers/ActivityTab.tsx
Labels: Release, Reviewed, Verified

#885 fix(ZNTA-2608): reset new language form fields on close or submit
  server/zanata-frontend/src/app/containers/Languages/NewLanguageModal.js
Labels: Ignore CodeCov, Release, Reviewed, Verified

#892 fix(ZNTA-2612) hide translation-comment search (can't show/edit)
  server/gwt-editor/src/main/java/org/zanata/webtrans/client/ui/EditorSearchField.ui.xml
Labels: Release, Reviewed, Verified

#875 feat(ZNTA-2528): refactor to ant notifications and alerts
  server/zanata-frontend/src/.storybook-frontend/__snapshots__/storyshots-frontend.test.js.snap
  server/zanata-frontend/src/app/components/Notification/Notification.story.js
  server/zanata-frontend/src/app/components/Notification/component.js
  server/zanata-frontend/src/app/components/Notification/index.js
  server/zanata-frontend/src/app/components/components.story.js
  server/zanata-frontend/src/app/components/index.js
  server/zanata-frontend/src/app/containers/Admin/Review.js
  server/zanata-frontend/src/app/containers/Glossary/index.js
  server/zanata-frontend/src/app/containers/Languages/index.js
  server/zanata-frontend/src/app/containers/UserProfile/index.jsx
  server/zanata-frontend/src/app/editor/reducers/review-trans-reducer.js
  server/zanata-frontend/src/app/editor/reducers/review-trans-reducer.test.js
  server/zanata-frontend/src/app/reducers/admin-reducer.js
  server/zanata-frontend/src/app/reducers/admin-reducer.test.js
  server/zanata-frontend/src/app/reducers/glossary-reducer.js
Labels: Ignore CodeCov, Reviewed, Verified

#888 fix: statistics update after save
  server/zanata-frontend/src/app/editor/actions/header-actions.js
  server/zanata-frontend/src/app/editor/actions/phrases-actions.js
  server/zanata-frontend/src/app/editor/reducers/phrase-reducer/index.js
  server/zanata-frontend/src/app/editor/reducers/phrase-reducer/phrase-reducer.test.js
Labels: Release, Reviewed, Verified

#887 fix(ZNTA-2617) add spacing to delete entry buttons on language page
  server/zanata-frontend/src/app/containers/Languages/DeleteEntry.js
  server/zanata-frontend/src/app/containers/Languages/index.js
Labels: Release, Reviewed, Verified

#846 chore(ZNTA-2390): run all tests if PR description contains allFuncTests
  Jenkinsfile
  build-tools/src/test/java/TestJenkinsfile.java
Labels: No QA (1st vote), No QA (2nd vote), Reviewed

#853 fix(ZNTA-2532) fix liquibase configuration
  server/etc/scripts/configure-app-server.js
  server/etc/scripts/runJbossCli.groovy
  server/etc/scripts/types.d.ts
  server/functional-test/pom.xml
  server/zanata-war/src/main/webapp/WEB-INF/liquibase
Labels: No QA (1st vote), No QA (2nd vote), Release, Reviewed

#835 Add some missing assertions
  server/functional-test/src/main/java/org/zanata/page/administration/ServerConfigurationPage.java
  server/functional-test/src/test/java/org/zanata/feature/account/InactiveUserLoginTest.java
  server/functional-test/src/test/java/org/zanata/feature/administration/ManageSearchTest.java
  server/functional-test/src/test/java/org/zanata/feature/administration/ServerSettingsTest.java
  server/functional-test/src/test/java/org/zanata/feature/document/MultiFileUploadTest.java
  server/functional-test/src/test/java/org/zanata/feature/project/EditProjectGeneralTest.java
Labels: Awaiting review, No QA (1st vote), No QA (2nd vote)

#894 fix(ZNTA-2620) user profile button styling
  server/zanata-frontend/src/app/containers/UserProfile/index.less
Labels: Release, Reviewed, Verified

#878 fix(ZNTA-2605): fix contact admin on Google log in
  server/services/src/main/resources/messages.properties
  server/zanata-war/src/main/webapp/account/google_password_reset_request.xhtml
Labels: Release, Reviewed, Verified

#877 feat(ZNTA-87): notify failed translation saves in alpha editor
  server/zanata-frontend/src/app/editor/actions/phrases-action-types.js
  server/zanata-frontend/src/app/editor/actions/phrases-actions.js
  server/zanata-frontend/src/app/editor/containers/TranslationInfoPanel/index.js
  server/zanata-frontend/src/app/editor/reducers/phrase-reducer/index.js
Labels: Reviewed, Verified

#862 fix(ZNTA-821): alpha editor to use zanata language setting as lang attribute
  server/zanata-frontend/src/app/editor/entrypoint/index.js
  server/zanata-war/src/main/webapp/editor/index.xhtml
Labels: Reviewed, Verified

#860 fix(ZNTA-2589) consistency of nav icons
  server/zanata-frontend/src/app/components/LogoLoader/index.less
  server/zanata-frontend/src/app/styles/frontend-nav.less
  server/zanata-frontend/src/app/styles/style.less
Labels: Release, Reviewed, Verified

#895 fix(ZNTA-2607) TMX modal styling
  server/zanata-frontend/src/app/components/TMX/TMXExportModal.js
  server/zanata-frontend/src/app/entrypoint/index.js
  server/zanata-frontend/src/app/styles/ant-theme-vars.less
  server/zanata-frontend/src/app/styles/antd.less
Labels: Release, Reviewed, Verified

#898 fix release-to-master conflicts
  server/zanata-frontend/src/app/components/TMX/TMXExportModal.js
  server/zanata-frontend/src/app/entrypoint/index.js
  server/zanata-frontend/src/app/styles/ant-theme-vars.less
  server/zanata-frontend/src/app/styles/antd.less
Labels: Awaiting review, Ignore CodeCov, No QA (1st vote), No QA (2nd vote)

#901 fix: project url in glossary page
  server/zanata-frontend/src/app/containers/Glossary/ViewHeader.js
Labels: Release, Reviewed, Verified

#896 fix: AddLanguageTest selenium id for notifications
  server/functional-test/src/main/java/org/zanata/page/BasePage.java
Labels: No QA (1st vote), No QA (2nd vote), Reviewed

#899 fix(ZNTA-2626): hide translation-comment search (can't show/edit)
  server/zanata-frontend/src/app/editor/components/EditorSearchInput/EditorSearchInput.test.js
  server/zanata-frontend/src/app/editor/components/EditorSearchInput/index.js
Labels: Release, Reviewed, Verified

#905 fix: loader text in button
  server/zanata-frontend/src/app/containers/Glossary/Entry.js
  server/zanata-frontend/src/app/containers/Glossary/EntryModal.js
  server/zanata-frontend/src/app/containers/Glossary/ExportModal.js
  server/zanata-frontend/src/app/containers/Glossary/ImportModal.js
  server/zanata-frontend/src/app/containers/Glossary/NewEntryModal.js
  server/zanata-frontend/src/app/styles/style.less
Labels: Reviewed, Verified

#907 Update to Kotlin 1.2.50; enable -Xprogressive
  server/pom.xml
Labels: No QA (1st vote), No QA (2nd vote), Reviewed

#908 fix: small ui changes
  server/zanata-frontend/src/app/containers/Explore/index.less
  server/zanata-frontend/src/app/containers/Glossary/EntryModal.js
  server/zanata-frontend/src/app/containers/Glossary/NewEntryModal.js
  server/zanata-frontend/src/app/containers/Glossary/index.less
  server/zanata-frontend/src/app/containers/Languages/NewLanguageModal.js
  server/zanata-frontend/src/app/containers/Languages/index.js
  server/zanata-frontend/src/app/containers/ProjectVersion/TMMergeProjectSources.js
  server/zanata-frontend/src/app/styles/antd.less
  server/zanata-frontend/src/app/styles/style.less
Labels: Release, Reviewed, Verified

#903 fix(test): Update e2e assert descriptions
  common/zanata-adapter-glossary/src/test/java/org/zanata/adapter/glossary/GlossaryCSVReaderTest.java
  server/functional-test/src/main/java/org/zanata/page/CorePage.java
  server/functional-test/src/test/java/org/zanata/feature/account/InactiveUserLoginTest.java
  server/functional-test/src/test/java/org/zanata/feature/administration/ManageSearchTest.java
  server/functional-test/src/test/java/org/zanata/feature/administration/ServerSettingsTest.java
  server/functional-test/src/test/java/org/zanata/feature/dashboard/DashboardTest.java
  server/functional-test/src/test/java/org/zanata/feature/document/DownloadDocumentTest.java
  server/functional-test/src/test/java/org/zanata/feature/document/MultiFileUploadTest.java
  server/functional-test/src/test/java/org/zanata/feature/editor/EditorAlphaTest.java
  server/functional-test/src/test/java/org/zanata/feature/endtoend/AdminEndToEndTest.java
  server/functional-test/src/test/java/org/zanata/feature/endtoend/UserEndToEndTest.java
  server/functional-test/src/test/java/org/zanata/feature/project/EditProjectGeneralTest.java
  server/services/src/test/java/org/zanata/adapter/AbstractAdapterTest.java
  server/services/src/test/java/org/zanata/adapter/TSAdapterTest.java
  server/services/src/test/java/org/zanata/adapter/XliffAdapterTest.java
Labels: No QA (1st vote), No QA (2nd vote), Release, Reviewed

#910 Fix console logger for EAP tests
  server/etc/scripts/configure-app-server.js
Labels: No QA (1st vote), No QA (2nd vote), Release

#902 fix: remove '0' notification label in gwt editor
  server/gwt-editor/src/main/java/org/zanata/webtrans/client/view/SideMenuView.java
Labels: Reviewed, Verified

#904 fix(ZNTA-2606): validate duplicate glossary entries
  server/services/src/main/java/org/zanata/service/impl/GlossaryFileServiceImpl.java
  server/zanata-frontend/src/app/containers/Glossary/index.js
  server/zanata-frontend/src/app/reducers/glossary-reducer.js
Labels: Ignore CodeCov, Release, Reviewed, Verified

#914 fix: use link component in admin home
  server/zanata-frontend/src/app/containers/Admin/Review.js
  server/zanata-frontend/src/app/containers/Admin/index.js
Labels: No QA (1st vote), No QA (2nd vote), Reviewed

#809 feat(ZNTA-75): Add live validations to React Editor
  server/functional-test/src/main/java/org/zanata/page/editor/ReactEditorPage.java
  server/zanata-frontend/src/.storybook-editor/__snapshots__/storyshots-editor.test.js.snap
  server/zanata-frontend/src/app/editor/components/TransUnitTranslationPanel.js
  server/zanata-frontend/src/app/editor/components/TransUnitTranslationPanel.test.js
  server/zanata-frontend/src/app/editor/components/Validation/Validation.story.js
  server/zanata-frontend/src/app/editor/components/Validation/Validation.test.js
  server/zanata-frontend/src/app/editor/components/Validation/index.tsx
  server/zanata-frontend/src/app/editor/containers/SettingsPanel.js
  server/zanata-frontend/src/app/utils/FeatureToggles.ts
  server/zanata-frontend/src/app/validators/AbstractValidationAction.ts
  server/zanata-frontend/src/app/validators/ValidationAction.ts
  server/zanata-frontend/src/app/validators/ValidationDisplayRules.ts
  server/zanata-frontend/src/app/validators/ValidationMessages.ts
  server/zanata-frontend/src/app/validators/impl/HtmlXmlTagValidation.test.js
  server/zanata-frontend/src/app/validators/impl/HtmlXmlTagValidation.ts
  server/zanata-frontend/src/app/validators/impl/JavaVariablesValidation.test.js
  server/zanata-frontend/src/app/validators/impl/JavaVariablesValidation.ts
  server/zanata-frontend/src/app/validators/impl/NewlineLeadTrailValidation.test.js
  server/zanata-frontend/src/app/validators/impl/NewlineLeadTrailValidation.ts
  server/zanata-frontend/src/app/validators/impl/PrintfVariablesValidation.test.js
  server/zanata-frontend/src/app/validators/impl/PrintfVariablesValidation.ts
  server/zanata-frontend/src/app/validators/impl/PrintfXSIExtensionValidation.test.js
  server/zanata-frontend/src/app/validators/impl/PrintfXSIExtensionValidation.ts
  server/zanata-frontend/src/app/validators/impl/TabValidation.test.js
  server/zanata-frontend/src/app/validators/impl/TabValidation.ts
  server/zanata-frontend/src/app/validators/impl/XmlEntityValidation.test.js
  server/zanata-frontend/src/app/validators/impl/XmlEntityValidation.ts
  server/zanata-frontend/src/app/validators/index.ts
  server/zanata-frontend/src/app/validators/messages/en.json
  server/zanata-frontend/src/app/validators/messages/fr.json
  server/zanata-frontend/src/app/validators/messages/index.ts
  server/zanata-frontend/src/app/validators/messages/ja.json
  server/zanata-frontend/src/messages/ja.json
  server/zanata-frontend/src/package.json
  server/zanata-frontend/src/tsconfig.json
  server/zanata-frontend/src/yarn.lock
Labels: Verified

#913 Merge release to master
  common/zanata-adapter-glossary/src/test/java/org/zanata/adapter/glossary/GlossaryCSVReaderTest.java
  server/etc/scripts/configure-app-server.js
  server/functional-test/src/main/java/org/zanata/page/CorePage.java
  server/functional-test/src/test/java/org/zanata/feature/dashboard/DashboardTest.java
  server/functional-test/src/test/java/org/zanata/feature/document/DownloadDocumentTest.java
  server/functional-test/src/test/java/org/zanata/feature/document/MultiFileUploadTest.java
  server/functional-test/src/test/java/org/zanata/feature/editor/EditorAlphaTest.java
  server/functional-test/src/test/java/org/zanata/feature/endtoend/AdminEndToEndTest.java
  server/functional-test/src/test/java/org/zanata/feature/endtoend/UserEndToEndTest.java
  server/services/src/test/java/org/zanata/adapter/AbstractAdapterTest.java
  server/services/src/test/java/org/zanata/adapter/TSAdapterTest.java
Labels: No QA (1st vote), No QA (2nd vote), Reviewed

#807 refactor(ZNTA-2514): react-bootstrap containers to antd
  server/zanata-frontend/src/.storybook-frontend/__snapshots__/storyshots-frontend.test.js.snap
  server/zanata-frontend/src/app/components/DraggableVersionPanels/DraggableVersionPanels.test.js
  server/zanata-frontend/src/app/components/DraggableVersionPanels/index.tsx
  server/zanata-frontend/src/app/components/EditableText/index.js
  server/zanata-frontend/src/app/components/LockIcon/LockIcon.test.js
  server/zanata-frontend/src/app/components/LockIcon/index.tsx
  server/zanata-frontend/src/app/components/ProgressBar/CancellableProgressBar.js
  server/zanata-frontend/src/app/components/ProgressBar/CancellableProgressBar.test.js
  server/zanata-frontend/src/app/containers/Admin/Review.js
  server/zanata-frontend/src/app/containers/Admin/index.js
  server/zanata-frontend/src/app/containers/Explore/TeaserListHeader.jsx
  server/zanata-frontend/src/app/containers/Explore/index.js
  server/zanata-frontend/src/app/containers/Glossary/DeleteAllEntriesModal.jsx
  server/zanata-frontend/src/app/containers/Glossary/DeleteEntryModal.jsx
  server/zanata-frontend/src/app/containers/Glossary/Entry.js
  server/zanata-frontend/src/app/containers/Glossary/EntryModal.js
  server/zanata-frontend/src/app/containers/Glossary/ExportModal.js
  server/zanata-frontend/src/app/containers/Glossary/Header.jsx
  server/zanata-frontend/src/app/containers/Glossary/ImportModal.js
  server/zanata-frontend/src/app/containers/Glossary/NewEntryModal.js
  server/zanata-frontend/src/app/containers/Glossary/ViewHeader.js
  server/zanata-frontend/src/app/containers/Glossary/index.js
  server/zanata-frontend/src/app/containers/Glossary/index.less
  server/zanata-frontend/src/app/containers/Languages/DeleteEntry.js
  server/zanata-frontend/src/app/containers/Languages/Entry.js
  server/zanata-frontend/src/app/containers/Languages/NewLanguageModal.js
  server/zanata-frontend/src/app/containers/Languages/index.js
  server/zanata-frontend/src/app/containers/ProjectVersion/ProjectVersionPanels.js
  server/zanata-frontend/src/app/containers/ProjectVersion/TMMergeImportedTM.js
  server/zanata-frontend/src/app/containers/ProjectVersion/TMMergeModal.js
  server/zanata-frontend/src/app/containers/ProjectVersion/TMMergeOptionsCommon.js
  server/zanata-frontend/src/app/containers/ProjectVersion/TMMergeProjectSources.js
  server/zanata-frontend/src/app/containers/ProjectVersion/TMMergeProjectTMOptions.js
  server/zanata-frontend/src/app/containers/ProjectVersion/index.less
  server/zanata-frontend/src/app/containers/ProjectVersion/project-version-displays.js
  server/zanata-frontend/src/app/containers/UserProfile/CalendarMonthMatrix.jsx
  server/zanata-frontend/src/app/containers/UserProfile/ContentStateFilter.jsx
  server/zanata-frontend/src/app/containers/UserProfile/DayMatrix.jsx
  server/zanata-frontend/src/app/containers/UserProfile/RecentContributions.jsx
  server/zanata-frontend/src/app/containers/UserProfile/index.less
  server/zanata-frontend/src/app/styles/ant-theme-vars.less
  server/zanata-frontend/src/app/styles/antd.less
Labels: Ignore CodeCov, Reviewed, Verified

#900 refactor(ZNTA-2622): use parameter objects for file format adapters/writers
  client/zanata-client-commands/src/main/java/org/zanata/client/commands/pull/GettextDirStrategy.java
  client/zanata-client-commands/src/main/java/org/zanata/client/commands/pull/GettextPullStrategy.java
  client/zanata-client-commands/src/main/java/org/zanata/client/commands/pull/PropertiesStrategy.java
  client/zanata-client-commands/src/main/java/org/zanata/client/commands/pull/PullCommand.java
  client/zanata-client-commands/src/main/java/org/zanata/client/commands/pull/PullStrategy.java
  client/zanata-client-commands/src/main/java/org/zanata/client/commands/pull/UTF8PropertiesStrategy.java
  client/zanata-client-commands/src/main/java/org/zanata/client/commands/pull/XliffStrategy.java
  client/zanata-client-commands/src/main/java/org/zanata/client/commands/pull/XmlStrategy.java
  client/zanata-client-commands/src/main/java/org/zanata/client/dto/LocaleMappedTranslatedDoc.java
  common/zanata-adapter-properties/src/main/java/org/zanata/adapter/properties/PropWriter.java
  common/zanata-adapter-properties/src/test/java/org/zanata/adapter/properties/PropReaderWriterTest.java
  common/zanata-common-util/src/main/java/org/zanata/common/dto/TranslatedDoc.java
  server/services/src/main/java/org/zanata/action/VersionHomeAction.java
  server/services/src/main/java/org/zanata/adapter/FileFormatAdapter.java
  server/services/src/main/java/org/zanata/adapter/FileFormatAdapter.kt
  server/services/src/main/java/org/zanata/adapter/GenericPropertiesAdapter.java
  server/services/src/main/java/org/zanata/adapter/GettextAdapter.java
  server/services/src/main/java/org/zanata/adapter/OkapiFilterAdapter.java
  server/services/src/main/java/org/zanata/adapter/TSAdapter.java
  server/services/src/main/java/org/zanata/adapter/XliffAdapter.java
  server/services/src/main/java/org/zanata/dao/DocumentDAO.java
  server/services/src/main/java/org/zanata/file/FilePersistService.java
  server/services/src/main/java/org/zanata/file/FileSystemPersistService.java
  server/services/src/main/java/org/zanata/file/SourceDocumentUpload.java
  server/services/src/main/java/org/zanata/rest/service/FileService.java
  server/services/src/main/java/org/zanata/service/TranslationFileService.java
  server/services/src/main/java/org/zanata/service/impl/TranslationFileServiceImpl.java
  server/services/src/test/java/org/zanata/adapter/AbstractAdapterTest.java
  server/services/src/test/java/org/zanata/adapter/DTDAdapterTest.java
  server/services/src/test/java/org/zanata/adapter/GettextAdapterTest.java
  server/services/src/test/java/org/zanata/adapter/IdmlAdapterTest.java
  server/services/src/test/java/org/zanata/adapter/JsonAdapterTest.java
  server/services/src/test/java/org/zanata/adapter/PlainTextAdapterTest.java
  server/services/src/test/java/org/zanata/adapter/PropertiesLatinOneAdapterTest.java
  server/services/src/test/java/org/zanata/adapter/PropertiesUTF8AdapterTest.java
  server/services/src/test/java/org/zanata/adapter/TSAdapterTest.java
  server/services/src/test/java/org/zanata/adapter/XliffAdapterTest.java
  server/services/src/test/java/org/zanata/file/DocumentUploadTest.java
  server/services/src/test/java/org/zanata/file/SourceDocumentUploadTest.java
  server/zanata-model/src/main/java/org/zanata/model/HDocument.java
Labels: No QA (1st vote), No QA (2nd vote), Reviewed

#917 fix: add antd import to root css in editor
  server/zanata-frontend/src/app/editor/containers/Root/index.css
  server/zanata-frontend/src/app/editor/entrypoint/index.js
Labels: No QA (1st vote), No QA (2nd vote), Reviewed

#919 ZNTA-2504: MTMerge modal story
  server/zanata-frontend/src/.storybook-frontend/__snapshots__/storyshots-frontend.test.js.snap
  server/zanata-frontend/src/.storybook-frontend/storybook.less
  server/zanata-frontend/src/app/components/Modal/Modal.story.js
  server/zanata-frontend/src/app/containers/ProjectVersion/MTMerge.js
  server/zanata-frontend/src/app/entrypoint/index.js
  server/zanata-frontend/src/app/styles/ant-theme-vars.less
  server/zanata-frontend/src/app/styles/antd.less
  server/zanata-frontend/src/app/styles/index.less
Labels: No QA (1st vote), No QA (2nd vote), Reviewed

#922 fix(ZNTA-2483): Fix context in TS file write
  server/services/src/main/java/org/zanata/adapter/TSAdapter.java
  server/services/src/test/java/org/zanata/adapter/TSAdapterTest.java
  server/services/src/test/resources/org/zanata/adapter/test-ts-untranslated.ts
Labels: Release, Reviewed, Verified

#921 refactor: eliminate some Guava
  build-tools/src/main/resources/zanata-build-tools/checkstyle.xml
  client/zanata-cli/src/test/java/org/zanata/client/BashCompletionGenerator.java
  client/zanata-client-commands/src/main/java/org/zanata/client/commands/push/PushCommand.java
  server/functional-test/src/main/java/org/zanata/page/projects/projectsettings/ProjectPermissionsTab.java
  server/functional-test/src/main/java/org/zanata/util/WebElementUtil.java
  server/functional-test/src/main/java/org/zanata/workflow/ClientWorkFlow.java
  server/functional-test/src/test/java/org/zanata/feature/misc/RateLimitRestAndUITest.java
  server/gwt-editor/src/main/java/org/zanata/webtrans/client/service/SaveEventQueue.java
  server/gwt-editor/src/main/java/org/zanata/webtrans/client/view/ValidationOptionsView.java
  server/services/src/main/java/org/zanata/action/DashboardAction.java
  server/services/src/main/java/org/zanata/action/LocaleSelectorAction.java
  server/services/src/main/java/org/zanata/action/ProjectHomeAction.java
  server/services/src/main/java/org/zanata/action/ProjectPermissionDialog.java
  server/services/src/main/java/org/zanata/action/VersionGroupHome.java
  server/services/src/main/java/org/zanata/action/VersionHome.java
  server/services/src/main/java/org/zanata/rest/service/ServerConfigurationService.java
  server/services/src/main/java/org/zanata/service/impl/TextFlowSearchServiceImpl.java
  server/services/src/main/java/org/zanata/service/impl/TranslationServiceImpl.java
  server/services/src/main/java/org/zanata/service/impl/WebhookServiceImpl.java
  server/services/src/main/java/org/zanata/ui/FilterUtil.java
  server/services/src/main/java/org/zanata/ui/InMemoryListFilter.java
  server/services/src/main/java/org/zanata/ui/autocomplete/LocaleAutocomplete.java
  server/services/src/main/java/org/zanata/util/QueryBuilder.java
  server/services/src/main/java/org/zanata/webtrans/server/rpc/GetTransUnitListHandler.java
  server/services/src/main/java/org/zanata/webtrans/server/rpc/GetTranslationHistoryHandler.java
  server/services/src/main/java/org/zanata/webtrans/server/rpc/UpdateTransUnitHandler.java
  server/services/src/test/java/org/zanata/dao/DocumentDAOTest.java
  server/services/src/test/java/org/zanata/dao/TextFlowTargetHistoryDAOTest.java
  server/services/src/test/java/org/zanata/limits/LeakyBucketTest.java
  server/services/src/test/java/org/zanata/model/DocumentJPATest.java
  server/services/src/test/java/org/zanata/model/HDocumentHistoryJPATest.java
  server/services/src/test/java/org/zanata/search/FilterConstraintToQueryJpaTest.java
  server/services/src/test/java/org/zanata/webtrans/server/rpc/GetProjectTransUnitListsHandlerTest.java
  server/services/src/test/java/org/zanata/webtrans/server/rpc/GetTransUnitListHandlerTest.java
  server/zanata-model/src/main/java/org/zanata/model/HApplicationConfiguration.java
  server/zanata-model/src/main/java/org/zanata/model/HPerson.java
  server/zanata-model/src/main/java/org/zanata/model/HProject.java
  server/zanata-model/src/main/java/org/zanata/model/HProjectLocaleMember.java
  server/zanata-model/src/main/java/org/zanata/model/HProjectMember.java
  server/zanata-model/src/main/java/org/zanata/model/PersonProjectMemberships.java
  server/zanata-test-war/src/main/java/org/zanata/rest/SampleDataResourceImpl.java
  server/zanata-war/src/test/java/org/zanata/webtrans/client/service/NavigationServiceIntegrationTest.java
Labels: No QA (1st vote), No QA (2nd vote), Reviewed

#915 Add MACHINE_TRANS to AUTOMATED_ENTRIES
  server/zanata-model/src/main/java/org/zanata/model/type/TranslationSourceType.java
Labels: No QA (1st vote), No QA (2nd vote)

#930 fix(ZNTA-2638) remove borders from antd buttons using btn-link styling
  server/zanata-frontend/src/app/containers/UserProfile/index.less
  server/zanata-frontend/src/app/styles/antd.less
Labels: Reviewed, Verified

#916 antd css fixes: minor ui fixes for consistency across frontend
  server/zanata-frontend/src/app/containers/ProjectVersion/TMMergeProjectSources.js
  server/zanata-frontend/src/app/styles/antd.less
  server/zanata-frontend/src/app/styles/style.less
Labels: Ignore CodeCov, No QA (1st vote), No QA (2nd vote), Reviewed

#929 Fix TypeScript settings
  server/zanata-frontend/src/.storybook-editor/__snapshots__/storyshots-editor.test.js.snap
  server/zanata-frontend/src/app/components/DraggableVersionPanels/DraggableVersionPanels.test.js
  server/zanata-frontend/src/app/components/Icon/index.tsx
  server/zanata-frontend/src/app/components/Modal/ModalFooter.tsx
  server/zanata-frontend/src/app/containers/ProjectVersion/MTMerge.js
  server/zanata-frontend/src/app/editor/components/CommentBox/index.tsx
  server/zanata-frontend/src/app/editor/components/GlossaryTerm/index.js
  server/zanata-frontend/src/app/editor/components/IconButton/IconButton.story.js
  server/zanata-frontend/src/app/editor/components/IconButton/IconButton.test.js
  server/zanata-frontend/src/app/editor/components/IconButton/index.js
  server/zanata-frontend/src/app/editor/components/NoSuggestionsPanel/NoSuggestionsPanel.test.js
  server/zanata-frontend/src/app/editor/components/TransUnitSourceHeader.js
  server/zanata-frontend/src/app/editor/components/TransUnitTranslationHeader.js
  server/zanata-frontend/src/app/editor/components/TransUnitTranslationPanel.test.js
  server/zanata-frontend/src/app/editor/components/Validation/Validation.test.js
  server/zanata-frontend/src/app/editor/components/Validation/index.tsx
  server/zanata-frontend/src/app/editor/components/components.story.js
  server/zanata-frontend/src/app/editor/containers/SuggestionsHeader.js
  server/zanata-frontend/src/app/editor/containers/TranslationInfoPanel/index.js
  server/zanata-frontend/src/app/require-all.test.ts
  server/zanata-frontend/src/app/validators/impl/JavaVariablesValidation.ts
  server/zanata-frontend/src/app/validators/impl/PrintfVariablesValidation.ts
  server/zanata-frontend/src/app/validators/impl/PrintfXSIExtensionValidation.ts
  server/zanata-frontend/src/tslint.json
  server/zanata-frontend/src/webpack.config.js
Labels: No QA (1st vote), No QA (2nd vote), Reviewed

#934 fix: nav link
  server/zanata-frontend/src/app/components/Link/index.js
  server/zanata-frontend/src/app/components/Nav/index.jsx
Labels: Reviewed, Verified

#936 fix(test): convert dashboard tests to Kotlin
  server/functional-test/src/test/java/org/zanata/feature/dashboard/DashboardTest.java
  server/functional-test/src/test/java/org/zanata/feature/dashboard/DashboardTest.kt
  server/functional-test/src/test/java/org/zanata/feature/dashboard/DashboardTestSuite.java
  server/functional-test/src/test/java/org/zanata/feature/dashboard/DashboardTestSuite.kt
Labels: No QA (1st vote), Reviewed

#918 refactor(ZNTA-2279): antd icons and select styling for glossary
  server/zanata-frontend/src/app/containers/Glossary/ViewHeader.js
  server/zanata-frontend/src/app/containers/Glossary/index.less
Labels: Ignore CodeCov, Reviewed, Verified

#942 fix: functional test
  server/functional-test/src/main/java/org/zanata/page/dashboard/dashboardsettings/DashboardClientTab.java
Labels: Awaiting review, No QA (1st vote)
