Repository zanata/zanata-platform, pull requests merged in 2018-03, with the labels that each got.

#739 Update to Kotlin 1.2.30
  server/pom.xml
Labels: No QA (1st vote), No QA (2nd vote), Reviewed

#738 fix(ZNTA-30) remove invalid char from TM Export
  server/services/src/main/java/org/zanata/rest/service/TranslationsTMXExportStrategy.java
  server/services/src/test/java/org/zanata/rest/service/ExportTranslationsTest.java
Labels: Reviewed, Verified

#742 fix(version page): show selected doc and locale
  server/zanata-war/src/main/webapp/WEB-INF/layout/version/documents-tab.xhtml
  server/zanata-war/src/main/webapp/WEB-INF/layout/version/languages-tab.xhtml
  server/zanata-war/src/main/webapp/iteration/view.xhtml
Labels: Reviewed, Verified

#740 refactor(ZNTA-2415): rejection modal and storybook
  server/zanata-frontend/src/.storybook-editor/__snapshots__/storyshots-editor.test.js.snap
  server/zanata-frontend/src/app/editor/app.css
  server/zanata-frontend/src/app/editor/components/RejectTranslationModal/CriteriaDropdown.js
  server/zanata-frontend/src/app/editor/components/RejectTranslationModal/CriteriaDropdown.test.js
  server/zanata-frontend/src/app/editor/components/RejectTranslationModal/PriorityDropdown.js
  server/zanata-frontend/src/app/editor/components/RejectTranslationModal/PriorityDropdown.test.js
  server/zanata-frontend/src/app/editor/components/RejectTranslationModal/RejectTranslationModal.story.js
  server/zanata-frontend/src/app/editor/components/RejectTranslationModal/RejectTranslationModalNoCrit.js
  server/zanata-frontend/src/app/editor/components/RejectTranslationModal/index.js
  server/zanata-frontend/src/app/editor/containers/MainContent.js
  server/zanata-frontend/src/app/editor/containers/RejectTranslation/index.css
  server/zanata-frontend/src/app/editor/containers/RejectTranslation/index.js
Labels: Reviewed, Verified

#746 docs: replace api doc host with github
  docs/index.md
  docs/user-guide/api/api.md
  parent/pom.xml
  pom.xml
Labels: No QA (1st vote), No QA (2nd vote), Release, Reviewed

#745 feat(ZNTA-2401): editor user mode display (Translating/Viewing/Reviewing)
  server/zanata-frontend/src/app/editor/components/TranslatingIndicator/TranslatingIndicator.test.js
  server/zanata-frontend/src/app/editor/components/TranslatingIndicator/index.js
  server/zanata-frontend/src/app/editor/containers/ControlsHeader.js
Labels: Reviewed, Verified

#743 Update to rewrite 3.4.2.Final
  server/pom.xml
Labels: Ignore CodeCov, No QA (1st vote), No QA (2nd vote)

#731 fix(ZNTA-2405): isolate frontend css
  server/functional-test/src/test/java/org/zanata/feature/administration/ServerSettingsTest.java
  server/zanata-frontend/src/app/components/Modal/index.jsx
  server/zanata-frontend/src/app/components/Nav/index.jsx
  server/zanata-frontend/src/app/containers/Admin/Review.js
  server/zanata-frontend/src/app/containers/Admin/index.less
  server/zanata-frontend/src/app/containers/App.js
  server/zanata-frontend/src/app/containers/Explore/index.less
  server/zanata-frontend/src/app/containers/Glossary/DeleteAllEntriesModal.jsx
  server/zanata-frontend/src/app/containers/Glossary/DeleteEntryModal.jsx
  server/zanata-frontend/src/app/containers/Glossary/index.less
  server/zanata-frontend/src/app/containers/Languages/DeleteEntry.js
  server/zanata-frontend/src/app/containers/Languages/Entry.js
  server/zanata-frontend/src/app/containers/Languages/index.js
  server/zanata-frontend/src/app/containers/Languages/index.less
  server/zanata-frontend/src/app/containers/UserProfile/RecentContributions.jsx
  server/zanata-frontend/src/app/containers/UserProfile/index.jsx
  server/zanata-frontend/src/app/containers/UserProfile/index.less
  server/zanata-frontend/src/app/editor/components/RejectTranslationModal/PriorityDropdown.js
  server/zanata-frontend/src/app/entrypoint/index.js
  server/zanata-frontend/src/app/styles/legacy.less
  server/zanata-frontend/src/app/styles/style.less
Labels: Ignore CodeCov, Reviewed, Verified

#751 fix(ZNTA-2423) fix & improve date formatting
  server/zanata-frontend/src/app/utils/DateHelper.ts
Labels: Reviewed, Verified

#752 doc: update zanata-cli installation command
  docs/client/installation/linux-installation.md
Labels: Reviewed, Verified

#623 Run JBoss CLI changes via API for more control
  .mvn/wrapper/maven-wrapper.properties
  Jenkinsfile
  server/etc/scripts/runJbossCli.groovy
  server/etc/scripts/zanata-config-arq-test.cli
  server/etc/scripts/zanata-config-test-common.cli
  server/etc/scripts/zanataConfigTest.groovy
  server/pom.xml
Labels: No QA (1st vote), No QA (2nd vote)

#755 Configure appserver using Nashorn script
  server/etc/scripts/configureAppServer.js
  server/etc/scripts/runJbossCli.groovy
  server/etc/scripts/zanataConfigTest.groovy
Labels: No QA (1st vote), No QA (2nd vote), Reviewed

#756 Make tuple elements readonly
  server/zanata-frontend/src/app/utils/tuple.ts
Labels: No QA (1st vote), No QA (2nd vote), Reviewed

#747 fix(ZNTA-2396): TM suggestion highlighting shows mismatched diff
  server/gwt-editor/src/main/java/org/zanata/webtrans/client/ui/DiffColorLegendPanel.ui.xml
  server/gwt-editor/src/main/java/org/zanata/webtrans/client/ui/Highlighting.java
  server/gwt-editor/src/main/java/org/zanata/webtrans/client/view/TransMemoryView.java
  server/gwt-editor/src/main/java/org/zanata/webtrans/client/view/TransMemoryView.ui.xml
  server/gwt-editor/src/main/webapp/webtrans/Application.xhtml
  server/services/pom.xml
  server/services/src/main/java/org/zanata/util/Webjars.kt
  server/zanata-frontend/src/.storybook-editor/__snapshots__/storyshots-editor.test.js.snap
  server/zanata-frontend/src/app/editor/components/TextDiff/TextDiff.test.js
  server/zanata-frontend/src/app/editor/components/TextDiff/index.js
  server/zanata-frontend/src/package.json
  server/zanata-frontend/src/yarn.lock
Labels: Ignore CodeCov, Reviewed, Verified

#754 fix(ZNTA-2429): language page height scroll
  server/zanata-frontend/src/app/containers/Languages/index.less
Labels: Ignore CodeCov, Reviewed, Verified

#729 feat(ZNTA-2297) Editor Activity Panel Backend
  server/gwt-editor/src/test/java/org/zanata/webtrans/client/presenter/TranslationHistoryPresenterTest.java
  server/gwt-shared/src/main/java/org/zanata/webtrans/shared/model/ReviewComment.java
  server/gwt-shared/src/main/java/org/zanata/webtrans/shared/model/TransHistoryItem.java
  server/gwt-shared/src/main/java/org/zanata/webtrans/shared/model/TransUnitUpdateRequest.java
  server/services/src/main/java/org/zanata/rest/editor/dto/TranslationData.java
  server/services/src/main/java/org/zanata/rest/editor/service/TransUnitHistoryService.java
  server/services/src/main/java/org/zanata/rest/editor/service/TranslationService.java
  server/services/src/main/java/org/zanata/rest/editor/service/resource/TransUnitHistoryResource.java
  server/services/src/main/java/org/zanata/rest/service/RestUtils.java
  server/services/src/main/java/org/zanata/webtrans/server/rpc/AddReviewCommentHandler.java
  server/services/src/main/java/org/zanata/webtrans/server/rpc/GetTranslationHistoryHandler.java
  server/services/src/test/java/org/zanata/rest/editor/dto/TranslationDataTest.java
  server/services/src/test/java/org/zanata/rest/editor/service/TransUnitHistoryServiceTest.java
  server/services/src/test/java/org/zanata/webtrans/server/rpc/GetTranslationHistoryHandlerTest.java
  server/zanata-frontend/src/.storybook-editor/__snapshots__/storyshots-editor.test.js.snap
  server/zanata-frontend/src/app/editor/actions/activity-action-types.js
  server/zanata-frontend/src/app/editor/actions/phrases-actions.js
  server/zanata-frontend/src/app/editor/actions/review-trans-actions.js
  server/zanata-frontend/src/app/editor/api/index.js
  server/zanata-frontend/src/app/editor/components/ActivityFeedItem/ActivityFeedItem.story.js
  server/zanata-frontend/src/app/editor/components/ActivityFeedItem/index.js
  server/zanata-frontend/src/app/editor/components/ActivitySelectList/index.js
  server/zanata-frontend/src/app/editor/components/CommentBox/index.tsx
  server/zanata-frontend/src/app/editor/components/TransUnit/index.js
  server/zanata-frontend/src/app/editor/containers/ActivityTab.js
  server/zanata-frontend/src/app/editor/containers/ActivityTab.tsx
  server/zanata-frontend/src/app/editor/containers/GlossaryTab.js
  server/zanata-frontend/src/app/editor/containers/MainContent.js
  server/zanata-frontend/src/app/editor/containers/RejectTranslation/index.js
  server/zanata-frontend/src/app/editor/containers/Sidebar/index.css
  server/zanata-frontend/src/app/editor/containers/TranslationInfoPanel/index.js
  server/zanata-frontend/src/app/editor/reducers/activity-reducer.js
  server/zanata-frontend/src/app/editor/reducers/index.js
  server/zanata-frontend/src/app/editor/utils/activity-util.ts
  server/zanata-frontend/src/app/editor/utils/phrase.ts
  server/zanata-model/src/main/java/org/zanata/model/HTextFlowTargetReviewComment.java
Labels: Reviewed, Verified

#758 Use xmlns:zanata in JSF, not xmlns:z
  server/zanata-war/src/main/webapp/WEB-INF/layout/project/people-tab.xhtml
  server/zanata-war/src/main/webapp/WEB-INF/layout/project/person-permissions-modal.xhtml
  server/zanata-war/src/main/webapp/resources/zanata/person-permission-entry.xhtml
Labels: No QA (1st vote), No QA (2nd vote)

#759 chore: fix deltaspike dependency
  server/pom.xml
  server/zanata-test-war/pom.xml
  server/zanata-war/pom.xml
Labels: No QA (1st vote), No QA (2nd vote), Reviewed

#757 Update Windows manual instructions
  docs/client/installation/windows-installation.md
Labels: Verified

#753 refactor(ZNTA-2407) isolate frontend container and component css
  server/zanata-frontend/src/.storybook-frontend/__snapshots__/storyshots-frontend.test.js.snap
  server/zanata-frontend/src/.storybook-frontend/config.js
  server/zanata-frontend/src/app/components/DraggableVersionPanels/index.tsx
  server/zanata-frontend/src/app/components/Notification/component.js
  server/zanata-frontend/src/app/components/ProgressBar/CancellableProgressBar.js
  server/zanata-frontend/src/app/components/ProgressBar/CancellableProgressBar.test.js
  server/zanata-frontend/src/app/components/RejectionsForm/index.js
  server/zanata-frontend/src/app/components/RejectionsForm/index.less
  server/zanata-frontend/src/app/components/SelectableDropdown/SelectableDropdown.test.js
  server/zanata-frontend/src/app/components/SelectableDropdown/index.js
  server/zanata-frontend/src/app/components/Sidebar/index.jsx
  server/zanata-frontend/src/app/components/Sidebar/index.less
  server/zanata-frontend/src/app/components/TMX/TMXExportModal.js
  server/zanata-frontend/src/app/components/TMX/index.less
  server/zanata-frontend/src/app/components/TriCheckbox/TriCheckbox.test.js
  server/zanata-frontend/src/app/components/TriCheckbox/index.js
  server/zanata-frontend/src/app/components/TriCheckbox/index.less
  server/zanata-frontend/src/app/containers/Admin/Review.js
  server/zanata-frontend/src/app/containers/Admin/index.less
  server/zanata-frontend/src/app/containers/Explore/TeaserListHeader.jsx
  server/zanata-frontend/src/app/containers/Explore/index.less
  server/zanata-frontend/src/app/containers/Glossary/EntryModal.js
  server/zanata-frontend/src/app/containers/Glossary/index.js
  server/zanata-frontend/src/app/containers/Glossary/index.less
  server/zanata-frontend/src/app/containers/Languages/index.less
  server/zanata-frontend/src/app/containers/ProjectVersion/index.less
  server/zanata-frontend/src/app/containers/UserProfile/index.jsx
  server/zanata-frontend/src/app/containers/UserProfile/index.less
  server/zanata-frontend/src/app/editor/components/Dropdown/Dropdown.test.js
  server/zanata-frontend/src/app/editor/components/Dropdown/index.css
  server/zanata-frontend/src/app/editor/components/Dropdown/index.js
  server/zanata-frontend/src/app/editor/components/EditorSearchInput/index.css
  server/zanata-frontend/src/app/editor/components/TranslatingIndicator/TranslatingIndicator.test.js
  server/zanata-frontend/src/app/editor/components/TranslatingIndicator/index.js
  server/zanata-frontend/src/app/editor/containers/ControlsHeader.js
  server/zanata-frontend/src/app/editor/containers/Root/index.css
  server/zanata-frontend/src/app/styles/legacy.less
  server/zanata-frontend/src/app/styles/style.less
Labels: Ignore CodeCov, Reviewed, Verified

#760 fix: remove sidebar from gwt editor
  server/gwt-editor/src/main/java/org/zanata/webtrans/client/ui/Breadcrumb.ui.xml
  server/gwt-editor/src/main/java/org/zanata/webtrans/client/view/AppView.ui.xml
  server/gwt-editor/src/main/webapp/webtrans/Application.xhtml
  server/zanata-frontend/src/app/styles/legacy.less
  server/zanata-war/src/main/webapp/resources/assets/css/gwt-editor.css
Labels: Reviewed, Verified

#762 fix(ZNTA-2446): increase clickable area for Update Translation modal
  server/zanata-frontend/src/app/styles/legacy.less
Labels: Reviewed, Verified

#750 feat(ZNTA-2425): Validation Options for Editor sidebar backend
  api/zanata-common-api/src/main/java/org/zanata/rest/service/ProjectVersionResource.java
  server/services/src/main/java/org/zanata/rest/service/ProjectVersionService.java
  server/services/src/test/java/org/zanata/rest/service/ProjectVersionServiceUnitTest.java
  server/services/src/test/java/org/zanata/rest/service/ProjectVersionTest.java
  server/zanata-frontend/src/app/editor/actions/header-actions.js
  server/zanata-frontend/src/app/editor/actions/settings-action-types.js
  server/zanata-frontend/src/app/editor/actions/settings-actions.js
  server/zanata-frontend/src/app/editor/components/SettingOption/index.js
  server/zanata-frontend/src/app/editor/components/SettingsOptions/index.js
  server/zanata-frontend/src/app/editor/containers/SettingsPanel.js
  server/zanata-frontend/src/app/editor/reducers/index.js
  server/zanata-frontend/src/app/editor/reducers/settings-reducer.js
  server/zanata-frontend/src/app/editor/reducers/settings-reducer.test.js
  server/zanata-frontend/src/app/editor/utils/validation-util.ts
  server/zanata-frontend/src/app/utils/FeatureToggles.ts
Labels: Reviewed, Verified
