Repository zanata/zanata-platform, pull requests merged in 2018-05, with the labels that each got.

#794 fix(ZNTA-2387): Add email and name to user search query
  server/services/src/main/java/org/zanata/dao/AccountDAO.java
Labels: Ignore CodeCov, Reviewed, Verified

#786 fix(ZNTA-2466) one wide and one centered layout for react frontend pages
  server/zanata-frontend/src/app/containers/Languages/index.less
  server/zanata-frontend/src/app/styles/style.less
Labels: Ignore CodeCov, Reviewed, Verified

#795 fix(ZNTA-2501) change copy to text icon in react editor
  server/zanata-frontend/src/.storybook-editor/__snapshots__/storyshots-editor.test.js.snap
  server/zanata-frontend/src/app/editor/components/ActivityFeedItem/index.js
Labels: Ignore CodeCov, Reviewed, Verified

#790 fix: add antd button information to storybook
  server/zanata-frontend/src/.storybook-frontend/__snapshots__/storyshots-frontend.test.js.snap
  server/zanata-frontend/src/app/components/Button/Button.story.js
Labels: No QA (1st vote), No QA (2nd vote), Reviewed

#771 perf(ZNTA-2459): improve activity panel / translationinfo panel performance
  server/zanata-frontend/src/app/editor/actions/header-action-types.js
  server/zanata-frontend/src/app/editor/actions/header-actions.js
  server/zanata-frontend/src/app/editor/actions/phrases-actions.js
  server/zanata-frontend/src/app/editor/components/Pager/Pager.test.tsx
  server/zanata-frontend/src/app/editor/components/Pager/index.js
  server/zanata-frontend/src/app/editor/components/TransUnit/index.js
  server/zanata-frontend/src/app/editor/containers/ActivityTab.tsx
  server/zanata-frontend/src/app/editor/containers/ControlsHeader.js
  server/zanata-frontend/src/app/editor/containers/MainContent.js
  server/zanata-frontend/src/app/editor/containers/Sidebar/index.css
  server/zanata-frontend/src/app/editor/containers/TranslationInfoPanel/DetailsPane.tsx
  server/zanata-frontend/src/app/editor/containers/TranslationInfoPanel/index.js
  server/zanata-frontend/src/app/editor/reducers/index.js
  server/zanata-frontend/src/app/editor/reducers/ui-reducer.js
  server/zanata-frontend/src/app/editor/reducers/ui-reducer.test.js
  server/zanata-frontend/src/app/editor/utils/activity-util.ts
  server/zanata-frontend/src/app/editor/utils/phrase.ts
  server/zanata-frontend/src/messages/ja.json
Labels: Ignore CodeCov, Reviewed, Verified

#805 feat: editor validation component and storybook
  server/zanata-frontend/src/app/editor/components/Validation/Validation.story.js
  server/zanata-frontend/src/app/editor/components/Validation/index.css
  server/zanata-frontend/src/app/editor/components/Validation/index.tsx
  server/zanata-frontend/src/app/editor/components/components.story.js
Labels: No QA (1st vote), No QA (2nd vote), Reviewed

#803 refactor(ZNTA-2508): add aria-label to antd buttons
  server/zanata-frontend/src/app/components/DraggableVersionPanels/DraggableVersionPanels.test.js
  server/zanata-frontend/src/app/components/DraggableVersionPanels/index.tsx
  server/zanata-frontend/src/app/components/Notification/component.js
  server/zanata-frontend/src/app/containers/Admin/Review.js
  server/zanata-frontend/src/app/containers/Explore/TeaserListHeader.jsx
  server/zanata-frontend/src/app/containers/Explore/index.js
  server/zanata-frontend/src/app/containers/Glossary/index.js
  server/zanata-frontend/src/app/containers/Languages/index.js
  server/zanata-frontend/src/app/containers/UserProfile/CalendarMonthMatrix.jsx
  server/zanata-frontend/src/app/containers/UserProfile/RecentContributions.jsx
Labels: Ignore CodeCov, Reviewed, Verified

#797 ZNTA-2495: antd tooltips and buttons
  server/zanata-frontend/src/.storybook-frontend/__snapshots__/storyshots-frontend.test.js.snap
  server/zanata-frontend/src/app/components/Button/Button.story.js
  server/zanata-frontend/src/app/components/DraggableVersionPanels/DraggableVersionPanels.test.js
  server/zanata-frontend/src/app/components/DraggableVersionPanels/index.tsx
  server/zanata-frontend/src/app/components/LockIcon/LockIcon.test.js
  server/zanata-frontend/src/app/components/LockIcon/index.tsx
  server/zanata-frontend/src/app/components/ProgressBar/CancellableProgressBar.js
  server/zanata-frontend/src/app/components/ProgressBar/CancellableProgressBar.test.js
  server/zanata-frontend/src/app/components/Sidebar/Sidebar.story.js
  server/zanata-frontend/src/app/components/Sidebar/index.jsx
  server/zanata-frontend/src/app/components/Tooltip/Tooltip.story.js
  server/zanata-frontend/src/app/containers/Admin/Review.js
  server/zanata-frontend/src/app/containers/Explore/TeaserListHeader.jsx
  server/zanata-frontend/src/app/containers/Explore/index.js
  server/zanata-frontend/src/app/containers/Glossary/DeleteAllEntriesModal.jsx
  server/zanata-frontend/src/app/containers/Glossary/DeleteEntryModal.jsx
  server/zanata-frontend/src/app/containers/Glossary/Entry.js
  server/zanata-frontend/src/app/containers/Glossary/EntryModal.js
  server/zanata-frontend/src/app/containers/Glossary/ExportModal.js
  server/zanata-frontend/src/app/containers/Glossary/ImportModal.js
  server/zanata-frontend/src/app/containers/Glossary/NewEntryModal.js
  server/zanata-frontend/src/app/containers/Glossary/ViewHeader.js
  server/zanata-frontend/src/app/containers/Glossary/index.js
  server/zanata-frontend/src/app/containers/Glossary/index.less
  server/zanata-frontend/src/app/containers/Languages/DeleteEntry.js
  server/zanata-frontend/src/app/containers/Languages/NewLanguageModal.js
  server/zanata-frontend/src/app/containers/Languages/index.js
  server/zanata-frontend/src/app/containers/UserProfile/ContentStateFilter.jsx
  server/zanata-frontend/src/app/containers/UserProfile/DayMatrix.jsx
  server/zanata-frontend/src/app/containers/UserProfile/RecentContributions.jsx
  server/zanata-frontend/src/app/containers/UserProfile/index.less
  server/zanata-frontend/src/app/entrypoint/index.js
  server/zanata-frontend/src/app/styles/style.less
Labels: Ignore CodeCov, Reviewed, Verified

#812 docs: update help url in cli
  client/zanata-client-commands/src/main/resources/prompts.properties
Labels: No QA (1st vote), No QA (2nd vote), Reviewed

#806 fix(ZNTA-860): Indicate username must start with a letter or number
  server/functional-test/src/main/java/org/zanata/page/account/RegisterPage.java
  server/services/src/main/java/org/zanata/action/HasUserDetail.java
  server/services/src/main/resources/ValidationMessages.properties
Labels: Reviewed, Verified

#810 Fix old Liquibase migrations
  server/services/src/main/java/org/zanata/liquibase/custom/CountWordsInHTextFlow.java
  server/services/src/main/java/org/zanata/liquibase/custom/GenerateHashForGlossaryEntry.java
  server/services/src/main/java/org/zanata/liquibase/custom/MigrateDataToHCredentials.java
  server/services/src/main/java/org/zanata/liquibase/custom/MigrateHTermCommentToString.java
  server/services/src/main/java/org/zanata/liquibase/custom/MigrateRawDocumentsToFileSystem.java
  server/services/src/main/java/org/zanata/liquibase/custom/RebuildTMXPlainText.java
  server/services/src/main/java/org/zanata/liquibase/custom/ValidateAccountPasswords.java
Labels: Ignore CodeCov, Release, Reviewed, Verified

#808 fix: include context path for doc and language link
  server/zanata-frontend/src/frontend/app/editor/components/DocsDropdown/index.js
  server/zanata-frontend/src/frontend/app/editor/components/LanguagesDropdown/index.js
Labels: Release, Reviewed, Verified

#799 refactor(ZNTA-2494): replace bootstrap modals with ant.design modals
  server/zanata-frontend/src/.storybook-frontend/__snapshots__/storyshots-frontend.test.js.snap
  server/zanata-frontend/src/app/components/Modal/Modal.story.js
  server/zanata-frontend/src/app/components/TMX/TMXExportModal.js
  server/zanata-frontend/src/app/containers/Glossary/ExportModal.js
  server/zanata-frontend/src/app/containers/Glossary/ImportModal.js
  server/zanata-frontend/src/app/containers/Glossary/NewEntryModal.js
  server/zanata-frontend/src/app/containers/Languages/NewLanguageModal.js
  server/zanata-frontend/src/app/containers/Languages/index.less
  server/zanata-frontend/src/app/containers/UserProfile/RecentContributions.jsx
  server/zanata-frontend/src/app/editor/components/GlossaryTermModal/component.js
  server/zanata-frontend/src/app/editor/components/RejectTranslationModal/CriteriaDropdown.js
  server/zanata-frontend/src/app/editor/components/RejectTranslationModal/CriteriaDropdown.test.js
  server/zanata-frontend/src/app/editor/components/RejectTranslationModal/PriorityDropdown.js
  server/zanata-frontend/src/app/editor/components/RejectTranslationModal/PriorityDropdown.test.js
  server/zanata-frontend/src/app/editor/components/RejectTranslationModal/index.js
  server/zanata-frontend/src/app/editor/containers/RejectTranslation/index.js
  server/zanata-frontend/src/app/editor/containers/SuggestionDetailsModal/index.js
  server/zanata-frontend/src/app/entrypoint/index.js
  server/zanata-frontend/src/app/styles/style.less
  server/zanata-frontend/src/app/utils/DateHelper.ts
Labels: Ignore CodeCov, Reviewed, Verified

#819 fix(ZNTA-2540): Reinstate anonymous admin contact
  server/functional-test/src/main/java/org/zanata/page/more/ContactAdminFormPage.java
  server/functional-test/src/test/java/org/zanata/feature/misc/ContactAdminTest.java
  server/services/src/main/resources/messages.properties
  server/services/src/test/java/org/zanata/email/EmailStrategyTest.java
  server/zanata-war/src/main/webapp/WEB-INF/layout/admin/contact_admin_modal.xhtml
  server/zanata-war/src/main/webapp/WEB-INF/layout/admin/contact_admin_modal_anonymous.xhtml
  server/zanata-war/src/main/webapp/public/info.xhtml
Labels: Reviewed, Verified

#814 fix(ZNTA-1993): Fix the role manager validation
  server/services/src/main/java/org/zanata/action/RoleAction.java
  server/services/src/main/java/org/zanata/seam/security/ZanataJpaIdentityStore.java
  server/services/src/main/resources/messages.properties
  server/services/src/test/java/org/zanata/action/RoleActionTest.java
  server/zanata-war/src/main/webapp/admin/roledetail.xhtml
Labels: Reviewed, Verified

#820 fix: glossary UI icon and project name overlap
  server/zanata-frontend/src/app/containers/Glossary/ViewHeader.js
Labels: Reviewed, Verified

#824 Refactor DBUnitProvider
  server/services/src/test/java/org/zanata/test/DBUnitDataSetRunner.java
  server/services/src/test/java/org/zanata/test/rule/DataSetOperation.java
  server/zanata-model-test/src/main/java/org/zanata/RestTest.java
  server/zanata-model-test/src/main/java/org/zanata/provider/DBUnitProvider.java
  server/zanata-war/src/test/java/org/zanata/ArquillianTest.java
Labels: No QA (1st vote), No QA (2nd vote)

#823 refactor: EmailStrategy to VelocityEmailStrategy
  server/services/src/main/java/org/zanata/action/ContactAdminAction.java
  server/services/src/main/java/org/zanata/action/ContactLanguageTeamMembersAction.java
  server/services/src/main/java/org/zanata/action/LanguageContactCoordinatorAction.java
  server/services/src/main/java/org/zanata/action/LanguageJoinAction.java
  server/services/src/main/java/org/zanata/action/VersionGroupJoinAction.java
  server/services/src/main/java/org/zanata/email/ActivationEmailStrategy.java
  server/services/src/main/java/org/zanata/email/ContactAdminAnonymousEmailStrategy.java
  server/services/src/main/java/org/zanata/email/ContactAdminEmailStrategy.java
  server/services/src/main/java/org/zanata/email/ContactLanguageCoordinatorEmailStrategy.java
  server/services/src/main/java/org/zanata/email/ContactLanguageTeamMembersEmailStrategy.java
  server/services/src/main/java/org/zanata/email/DeclineLanguageRequestEmailStrategy.java
  server/services/src/main/java/org/zanata/email/EmailBuilder.java
  server/services/src/main/java/org/zanata/email/EmailValidationEmailStrategy.java
  server/services/src/main/java/org/zanata/email/LanguageTeamPermissionChangeEmailStrategy.java
  server/services/src/main/java/org/zanata/email/PasswordResetEmailStrategy.java
  server/services/src/main/java/org/zanata/email/RequestToJoinLanguageEmailStrategy.java
  server/services/src/main/java/org/zanata/email/RequestToJoinVersionGroupEmailStrategy.java
  server/services/src/main/java/org/zanata/email/UsernameChangedEmailStrategy.java
  server/services/src/main/java/org/zanata/email/VelocityEmailStrategy.java
  server/services/src/main/java/org/zanata/service/EmailService.java
  server/services/src/main/java/org/zanata/service/impl/EmailServiceImpl.java
  server/services/src/main/java/org/zanata/service/impl/RequestServiceImpl.java
  server/services/src/test/java/org/zanata/action/ContactAdminActionTest.java
  server/services/src/test/java/org/zanata/email/VelocityEmailStrategyTest.java
Labels: No QA (1st vote), No QA (2nd vote), Reviewed

#829 fix: AddLanguageTest selenium ids
  server/functional-test/src/main/java/org/zanata/page/administration/AddLanguagePage.java
  server/functional-test/src/test/java/org/zanata/feature/language/AddLanguageTest.java
  server/zanata-frontend/src/app/containers/Languages/NewLanguageModal.js
Labels: Reviewed, Verified

#811 ZNTA-2492 erase a user and its data
  server/services/src/main/java/org/zanata/action/UserAction.java
  server/services/src/main/java/org/zanata/exception/DeleteUserConstraintException.java
  server/services/src/main/java/org/zanata/exception/handler/DeleteUserConstraintExceptionHandler.java
  server/services/src/main/java/org/zanata/file/DocumentStorage.java
  server/services/src/main/java/org/zanata/file/FileSystemPersistService.java
  server/services/src/main/java/org/zanata/service/UserAccountService.java
  server/services/src/main/java/org/zanata/service/impl/UserAccountServiceImpl.java
  server/services/src/main/resources/db/changelogs/db.changelog-4.5.xml
  server/services/src/main/resources/messages.properties
  server/services/src/test/java/org/zanata/ZanataJpaTest.java
  server/services/src/test/java/org/zanata/dao/TextFlowTargetHistoryDAOTest.java
  server/services/src/test/java/org/zanata/search/FilterConstraintToQueryJpaTest.java
  server/services/src/test/java/org/zanata/service/impl/UserAccountServiceImplTest.java
  server/zanata-model-test/src/main/resources/org/zanata/test/model/AccountData.dbunit.xml
  server/zanata-model-test/src/main/resources/performance/GetTransUnitListTest.dbunit.xml
  server/zanata-model/src/main/java/org/zanata/model/Eraseable.java
  server/zanata-model/src/main/java/org/zanata/model/HAccount.java
  server/zanata-model/src/main/java/org/zanata/model/HIterationGroup.java
  server/zanata-model/src/main/java/org/zanata/model/HPerson.java
  server/zanata-model/src/main/java/org/zanata/model/HProject.java
  server/zanata-model/src/main/java/org/zanata/model/validator/UniqueValidator.java
  server/zanata-war/src/main/webapp-jboss/WEB-INF/classes/META-INF/persistence.xml
  server/zanata-war/src/main/webapp/admin/usermanager.xhtml
Labels: Reviewed, Verified

#831 fix(ZNTA-2554): remove ant design badge component
  server/zanata-frontend/src/app/components/TMX/TMXExportModal.js
  server/zanata-frontend/src/app/styles/antd.less
Labels: Reviewed, Verified

#838 fix(ZNTA-2567) allow TM Merge (project version) to be cancelled
  server/services/src/main/java/org/zanata/service/TransMemoryMergeService.java
  server/services/src/main/java/org/zanata/service/tm/merge/TransMemoryMergeServiceImpl.java
Labels: Release, Reviewed, Verified

#837 fix(ZNTA-2141): escape Lucene keywords more precisely
  server/services/src/main/java/org/zanata/service/impl/TranslationMemoryServiceImpl.java
  server/services/src/test/java/org/zanata/service/impl/TranslationMemoryServiceImplUnitTest.java
  server/services/src/test/java/org/zanata/service/impl/TranslationMemoryServiceImplUnitTest.kt
Labels: Release, Reviewed, Verified

#842 fix(ZNTA-2569): add locale ID to the TM Merge report
  server/services/src/main/java/org/zanata/email/TMMergeEmailStrategy.kt
  server/services/src/main/java/org/zanata/service/tm/merge/TransMemoryMergeServiceImpl.java
  server/services/src/main/resources/messages.properties
  server/services/src/test/java/org/zanata/email/HtmlEmailBuilderTest.kt
Labels: Release, Reviewed, Verified

#843 fix(ZNTA-2552): Cookie consent banner
  server/functional-test/src/main/java/org/zanata/page/AbstractPage.kt
  server/zanata-frontend/src/app/styles/style.less
  server/zanata-war/src/main/webapp/WEB-INF/template/template.xhtml
  server/zanata-war/src/main/webapp/WEB-INF/template/template_nobanner.xhtml
Labels: Release, Reviewed, Verified

#840 fix(ZNTA-2522) added spacing between languages on user profile
  server/zanata-frontend/src/app/containers/UserProfile/index.jsx
  server/zanata-frontend/src/app/containers/UserProfile/index.less
Labels: Ignore CodeCov, Release, Reviewed, Verified

#845 fix: invalid group link in version page
  server/zanata-war/src/main/webapp/WEB-INF/layout/version/groups-tab.xhtml
Labels: Release, Reviewed, Verified

#833 fix(ZNTA-2561): Jenkinsfile: preprocess node should be kept minimal
  Jenkinsfile
Labels: Awaiting review, No QA (1st vote), No QA (2nd vote), Release

#844 Improve TraceDebugFilter; add debug for FileResourceClientTest
  client/zanata-client-commands/src/main/java/org/zanata/client/commands/ConfigurableOptionsImpl.java
  client/zanata-rest-client/src/main/java/org/zanata/rest/client/TraceDebugFilter.java
  client/zanata-rest-client/src/test/java/org/zanata/rest/client/FileResourceClientTest.java
Labels: Reviewed, Verified

#848 fix: unique html id for checkbox
  server/zanata-war/src/main/webapp/WEB-INF/layout/project/languages-list.xhtml
  server/zanata-war/src/main/webapp/resources/zanata/select-all-checkbox.xhtml
Labels: Release, Reviewed, Verified

#847 Update JavaMelody to 1.72.0
  server/services/pom.xml
  server/zanata-war/pom.xml
Labels: Reviewed, Verified

#850 fix(ZNTA-2574) group pages styling fixes
  server/zanata-frontend/src/app/styles/frontend-jsf.less
Labels: Release, Reviewed, Verified

#851 test(ZNTA-2532): run liquibase script for tests
  server/functional-test/pom.xml
  server/functional-test/src/test/resources/liquibase.properties
Labels: No QA (1st vote), No QA (2nd vote), Release, Reviewed

#841 fix(ZNTA-2517) add ellipsis to delete group modal
  server/zanata-frontend/src/app/styles/frontend-jsf.less
  server/zanata-war/src/main/webapp/WEB-INF/layout/version-group/delete_group_confirmation_modal.xhtml
Labels: Ignore CodeCov, Release, Reviewed, Verified

#852 feat: display projects in dashboard for member and maintainer
  server/functional-test/src/main/java/org/zanata/page/dashboard/DashboardProjectsTab.java
  server/services/src/main/java/org/zanata/action/DashboardAction.java
  server/services/src/main/java/org/zanata/dao/ProjectDAO.java
  server/services/src/main/resources/messages.properties
  server/services/src/test/java/org/zanata/dao/ProjectDAOTest.java
  server/zanata-war/src/main/webapp/WEB-INF/layout/dashboard/projects.xhtml
Labels: Reviewed, Verified

#857 fix: release-to-master merge conflicts
  server/zanata-frontend/src/app/styles/frontend-jsf.less
  server/zanata-war/src/main/webapp/WEB-INF/layout/version-group/delete_group_confirmation_modal.xhtml
Labels: No QA (1st vote), No QA (2nd vote), Reviewed

#856 refactor(ZNTA-2584): EditorSearchInput to use Ant Collapse
  server/zanata-frontend/src/app/editor/components/EditorSearchInput/EditorSearchInput.test.js
  server/zanata-frontend/src/app/editor/components/EditorSearchInput/index.css
  server/zanata-frontend/src/app/editor/components/EditorSearchInput/index.js
Labels: Reviewed, Verified

#817 refactor(ZNTA-2538): RejectionsForm bootstap components to ant design
  server/zanata-frontend/src/.storybook-frontend/__snapshots__/storyshots-frontend.test.js.snap
  server/zanata-frontend/src/app/components/RejectionsForm/RejectionsForm.story.js
  server/zanata-frontend/src/app/components/RejectionsForm/index.js
  server/zanata-frontend/src/app/containers/Admin/Review.js
  server/zanata-frontend/src/app/styles/ant-theme-vars.less
Labels: Reviewed, Verified

#832 test(ZNTA-2559): use waitForPageSilence, not Thread.sleep
  server/functional-test/src/main/java/org/zanata/page/AbstractPage.kt
  server/functional-test/src/main/java/org/zanata/page/administration/ManageSearchPage.java
  server/functional-test/src/main/java/org/zanata/page/projectversion/versionsettings/VersionTranslationTab.java
Labels: No QA (1st vote), No QA (2nd vote), Reviewed

#859 fix: cleanup obsolete groups
  server/services/src/main/java/org/zanata/dao/VersionGroupDAO.java
  server/services/src/main/java/org/zanata/rest/search/dto/GroupSearchResult.java
  server/services/src/main/java/org/zanata/rest/search/service/SearchService.java
  server/services/src/main/java/org/zanata/security/SecurityFunctions.java
  server/services/src/main/resources/db/changelogs/db.changelog-4.6.xml
  server/services/src/main/resources/db/db.changelog.xml
  server/zanata-frontend/src/app/containers/Explore/GroupTeaser.jsx
  server/zanata-model-test/src/main/resources/org/zanata/test/model/CopyVersionData.dbunit.xml
  server/zanata-model-test/src/main/resources/org/zanata/test/model/GroupsTestData.dbunit.xml
  server/zanata-model/src/main/java/org/zanata/model/HIterationGroup.java
Labels: Reviewed, Verified
