Repository zanata/zanata-platform, pull requests merged in 2018-08, with the labels that each got.

#1009 fix(ZNTA-2727): TM Merge modal version filter check, remove componentWillReceiveProps
  server/zanata-frontend/src/app/containers/ProjectVersion/TMMergeModal.js
  server/zanata-frontend/src/app/containers/ProjectVersion/TMMergeProjectSources.js
Labels: Ignore CodeCov, Release, Reviewed, Verified

#1005 refactor(ZNTA-2715) replace react-date-range component with antd DatePicker
  server/zanata-frontend/src/app/containers/UserProfile/RecentContributions.jsx
  server/zanata-frontend/src/app/containers/UserProfile/index.jsx
  server/zanata-frontend/src/app/containers/UserProfile/index.less
  server/zanata-frontend/src/app/styles/antd.less
  server/zanata-frontend/src/package.json
Labels: Ignore CodeCov, Reviewed, Verified

#1006 refactor(ZNTA-2722): clean up assets scripts
  server/zanata-war/src/main/webapp/WEB-INF/template/scripts.xhtml
  server/zanata-war/src/main/webapp/resources/assets/bootstrap.min.js
  server/zanata-war/src/main/webapp/resources/assets/script.js
  server/zanata-war/src/main/webapp/resources/assets/zanata.js
Labels: Reviewed, Verified

#1004 fix(ZNTA-2721): batch requests to server
  server/services/src/main/java/org/zanata/service/impl/MachineTranslationServiceImpl.java
Labels: Release, Reviewed, Verified

#1014 feat(ZNTA-2580): sorted and searchable locale select for TM Merge
  server/zanata-frontend/src/app/components/LocaleSelect/index.tsx
  server/zanata-frontend/src/app/components/MTMerge/MTMergeOptions.tsx
  server/zanata-frontend/src/app/containers/ProjectVersion/TMMergeModal.js
Labels: Release, Reviewed, Verified

#1012 fix: disable trans merge if empty document
  server/zanata-war/src/main/webapp/iteration/view.xhtml
Labels: Reviewed, Verified

#1013 fix(ZNTA-2730): clear hibernate cache before and after batch
  server/services/src/main/java/org/zanata/service/impl/MachineTranslationServiceImpl.java
Labels: Release, Verified

#1018 fix: hide MT merge option if without URL
  server/services/src/main/java/org/zanata/action/VersionHomeAction.java
  server/zanata-war/src/main/webapp/iteration/view.xhtml
Labels: On QA, Release, Reviewed, Verified

#1015 fix(ZNTA-2735): pass strings to MT as text/xml
  server/services/src/main/java/org/zanata/service/mt/dto/TypeString.java
Labels: Verified

#1017 fix: ZNTA-2740: role details exception
  server/zanata-war/src/main/webapp/admin/roledetail.xhtml
Labels: Ignore CodeCov, Release, Reviewed, Verified

#1021 feat(async): add a Tasks tab to dashboard
  server/services/src/main/java/org/zanata/action/CopyTransManager.java
  server/services/src/main/java/org/zanata/action/CopyVersionManager.java
  server/services/src/main/java/org/zanata/action/DashboardAction.java
  server/services/src/main/java/org/zanata/action/MergeTranslationsManager.java
  server/services/src/main/java/org/zanata/async/AsyncTaskHandle.java
  server/services/src/main/java/org/zanata/async/AsyncTaskHandleManager.java
  server/services/src/main/java/org/zanata/async/handle/CopyTransTaskHandle.java
  server/services/src/main/java/org/zanata/async/handle/CopyVersionTaskHandle.java
  server/services/src/main/java/org/zanata/async/handle/MachineTranslationPrefillTaskHandle.java
  server/services/src/main/java/org/zanata/async/handle/MergeTranslationsTaskHandle.java
  server/services/src/main/java/org/zanata/async/handle/TransMemoryMergeTaskHandle.java
  server/services/src/main/java/org/zanata/rest/editor/service/TransMemoryMergeManager.java
  server/services/src/main/java/org/zanata/rest/service/MachineTranslationsManager.java
  server/services/src/main/java/org/zanata/service/impl/MachineTranslationServiceImpl.java
  server/services/src/main/resources/messages.properties
  server/services/src/test/java/org/zanata/async/AsyncTaskHandleManagerTest.kt
  server/services/src/test/java/org/zanata/rest/editor/service/TransMemoryMergeManagerTest.java
  server/services/src/test/java/org/zanata/rest/service/AsyncProcessServiceTest.java
  server/zanata-war/src/main/webapp/WEB-INF/layout/dashboard/tasks.xhtml
  server/zanata-war/src/main/webapp/dashboard/home.xhtml
Labels: Reviewed, Verified

#1022 chore: update to TypeScript 3
  server/zanata-frontend/src/package.json
  server/zanata-frontend/src/yarn.lock
Labels: Reviewed, Verified

#1023 fix(ZNTA-2751): translation file upload permission
  server/zanata-war/src/main/webapp/WEB-INF/layout/version/languages-tab.xhtml
Labels: Release, Reviewed, Verified

#1024 README: Fix link to Docker docs
  README.md
Labels: Reviewed, Verified

#1020 fix(ZNTA-2745): use function to check for documents in version
  server/services/src/main/java/org/zanata/action/VersionHomeAction.java
  server/services/src/test/java/org/zanata/action/VersionHomeActionTest.kt
  server/zanata-war/src/main/webapp/iteration/view.xhtml
Labels: Release, Reviewed, Verified

#1025 chore: upgrade to Mockito-Kotlin 2
  server/pom.xml
  server/services/pom.xml
  server/services/src/test/java/org/zanata/action/FrontendAssetsTest.kt
  server/services/src/test/java/org/zanata/action/VersionHomeActionTest.kt
  server/services/src/test/java/org/zanata/dao/CredentialsDAOTest.kt
  server/services/src/test/java/org/zanata/rest/RestLimitingFilterTest.kt
  server/services/src/test/java/org/zanata/security/AuthenticationManagerTest.kt
  server/services/src/test/java/org/zanata/security/SamlAccountServiceTest.kt
  server/services/src/test/java/org/zanata/servlet/SAMLFilterTest.kt
  server/services/src/test/java/org/zanata/ui/faces/FacesMessagesTest.kt
  server/zanata-war/pom.xml
Labels: No QA (1st vote), No QA (2nd vote), Release, Reviewed

#1026 chore: use argumentCaptor
  server/services/src/test/java/org/zanata/rest/RestLimitingFilterTest.kt
Labels: No QA (1st vote), No QA (2nd vote), Reviewed

#1029 refactor: remove google and myopenid provider
  server/services/src/main/java/org/zanata/action/LoginAction.java
  server/services/src/main/java/org/zanata/action/UserSettingsAction.java
  server/services/src/main/java/org/zanata/security/ZanataOpenId.java
  server/services/src/main/java/org/zanata/security/openid/GoogleOpenIdProvider.java
  server/services/src/main/java/org/zanata/security/openid/MyOpenIdProvider.java
  server/services/src/main/java/org/zanata/security/openid/OpenIdProviderType.java
  server/services/src/main/java/org/zanata/servlet/UrlRewriteConfig.java
  server/zanata-war/src/main/webapp/account/google_password_reset_request.xhtml
  server/zanata-war/src/main/webapp/account/login.xhtml
  server/zanata-war/src/main/webapp/profile/merge_account.xhtml
Labels: Reviewed, Verified

#1032 Increase JS heap
  Jenkinsfile
Labels: No QA (1st vote), No QA (2nd vote), Reviewed

#1027 Replace Javaslang with Cyclops X
  server/pom.xml
  server/services/pom.xml
  server/services/src/main/java/org/zanata/action/VersionHome.java
  server/services/src/main/java/org/zanata/email/ActivationEmailStrategy.java
  server/services/src/main/java/org/zanata/email/ContactAdminAnonymousEmailStrategy.java
  server/services/src/main/java/org/zanata/email/ContactAdminEmailStrategy.java
  server/services/src/main/java/org/zanata/email/ContactLanguageCoordinatorEmailStrategy.java
  server/services/src/main/java/org/zanata/email/ContactLanguageTeamMembersEmailStrategy.java
  server/services/src/main/java/org/zanata/email/DeclineLanguageRequestEmailStrategy.java
  server/services/src/main/java/org/zanata/email/EmailBuilder.java
  server/services/src/main/java/org/zanata/email/EmailValidationEmailStrategy.java
  server/services/src/main/java/org/zanata/email/LanguageTeamPermissionChangeEmailStrategy.java
  server/services/src/main/java/org/zanata/email/PasswordResetEmailStrategy.java
  server/services/src/main/java/org/zanata/email/RequestToJoinLanguageEmailStrategy.java
  server/services/src/main/java/org/zanata/email/RequestToJoinVersionGroupEmailStrategy.java
  server/services/src/main/java/org/zanata/email/UsernameChangedEmailStrategy.java
  server/services/src/main/java/org/zanata/email/VelocityEmailStrategy.java
  server/services/src/main/java/org/zanata/rest/ZanataRestSecurityInterceptor.java
  server/services/src/main/java/org/zanata/rest/editor/service/TransUnitHistoryService.java
  server/services/src/main/java/org/zanata/rest/editor/service/TransUnitHistoryService.kt
  server/services/src/main/java/org/zanata/rest/editor/service/resource/TransUnitHistoryResource.java
  server/services/src/main/java/org/zanata/rest/service/RestUtils.java
  server/services/src/test/java/org/zanata/arquillian/classes.kt
  server/services/src/test/java/org/zanata/rest/editor/service/TransUnitHistoryServiceTest.java
  server/services/src/test/java/org/zanata/rest/service/raw/ArquillianRest.kt
  server/zanata-war/pom.xml
Labels: No QA (1st vote), No QA (2nd vote), Reviewed

#1028 fix(ZNTA-2753): unify the version is active check
  parent/pom.xml
  server/services/src/main/java/org/zanata/action/ProjectHome.java
  server/services/src/main/java/org/zanata/action/ProjectHomeAction.java
  server/services/src/main/java/org/zanata/action/VersionHome.java
  server/services/src/main/java/org/zanata/action/VersionHomeAction.java
  server/services/src/main/java/org/zanata/file/DocumentUploadUtil.java
  server/services/src/main/java/org/zanata/file/SourceDocumentUpload.java
  server/services/src/main/java/org/zanata/file/TranslationDocumentUpload.java
  server/services/src/main/java/org/zanata/rest/editor/service/TranslationReviewService.java
  server/services/src/main/java/org/zanata/service/impl/SecurityServiceImpl.java
  server/services/src/main/java/org/zanata/webtrans/server/TranslationWorkspaceManagerImpl.java
  server/services/src/main/java/org/zanata/webtrans/server/rpc/ActivateWorkspaceHandler.java
  server/services/src/main/resources/messages.properties
  server/services/src/test/java/org/zanata/action/VersionHomeActionTest.kt
  server/services/src/test/java/org/zanata/file/DocumentUploadTest.java
  server/services/src/test/java/org/zanata/file/DocumentUploadUtilTest.java
  server/services/src/test/java/org/zanata/file/SourceDocumentUploadTest.java
  server/services/src/test/java/org/zanata/webtrans/server/rpc/ActivateWorkspaceHandlerTest.java
  server/zanata-model/src/main/java/org/zanata/model/HProjectIteration.java
  server/zanata-war/src/main/webapp/resources/zanata/version-label.xhtml
Labels: Reviewed, Verified

#1033 refactor: use Either.bipeek
  server/services/src/main/java/org/zanata/rest/ZanataRestSecurityInterceptor.java
Labels: No QA (1st vote), No QA (2nd vote), Reviewed

#982 chore(ZNTA-2694): Upgrade Okapi to M36
  common/zanata-common-util/src/test/java/org/zanata/util/HashUtilTest.java
  server/pom.xml
  server/services/src/test/java/org/zanata/adapter/TSAdapterTest.kt
  server/services/src/test/java/org/zanata/rest/service/ResourceUtilsTest.java
  server/services/src/test/java/org/zanata/service/impl/CopyVersionServiceImplTest.java
  server/zanata-model/src/test/java/org/zanata/util/OkapiUtilTest.java
Labels: Reviewed, Verified

#1037 Update JaCoCo (filters out Kotlin codegen)
  parent/pom.xml
Labels: No QA (1st vote), No QA (2nd vote), Reviewed

#1038 chore: update to CDI-Unit 4.1.0
  server/pom.xml
Labels: No QA (1st vote), No QA (2nd vote), Reviewed

#1016 fix(ZNTA-2710) Increase MT progress granularity
  server/services/src/main/java/org/zanata/async/handle/MachineTranslationPrefillTaskHandle.java
  server/services/src/main/java/org/zanata/service/impl/MachineTranslationServiceImpl.java
  server/services/src/test/java/org/zanata/async/MachineTranslationPrefillTaskHandleTest.kt
  server/services/src/test/java/org/zanata/service/impl/MachineTranslationServiceImplTest.java
Labels: Reviewed, Verified

#1040 chore: update docker-compose.yml to add healthcheck
  server/docker/docker-compose.yml
Labels: No QA (1st vote), No QA (2nd vote)

#1039 chore: remove omnifaces
  server/zanata-war/pom.xml
  server/zanata-war/src/main/webapp/WEB-INF/layout/project/person-permissions-modal.xhtml
  server/zanata-war/src/main/webapp/resources/script/jsf-ajax-viewstate-fix.js
Labels: Reviewed, Verified
