Repository zanata/zanata-platform, pull requests merged in 2018-07, with the labels that each got.

#882 chore(ZNTA-2610): upgrade react to 16.4.0
  server/zanata-frontend/src/.storybook-editor/__snapshots__/storyshots-editor.test.js.snap
  server/zanata-frontend/src/.storybook-editor/addons.js
  server/zanata-frontend/src/.storybook-editor/config.js
  server/zanata-frontend/src/.storybook-editor/storyshots-editor.test.js
  server/zanata-frontend/src/.storybook-frontend/__snapshots__/storyshots-frontend.test.js.snap
  server/zanata-frontend/src/app/components/Modal/Modal.story.js
  server/zanata-frontend/src/app/components/Modal/index.jsx
  server/zanata-frontend/src/app/components/Notification/component.js
  server/zanata-frontend/src/app/components/Tooltip/Tooltip.story.js
  server/zanata-frontend/src/app/components/components.story.js
  server/zanata-frontend/src/app/containers/Glossary/EntryModal.js
  server/zanata-frontend/src/app/editor/components/EditorSearchInput/index.js
  server/zanata-frontend/src/app/editor/components/GlossaryTermModal/GlossaryTermModal.story.js
  server/zanata-frontend/src/app/editor/components/Pager/Pager.test.tsx
  server/zanata-frontend/src/app/editor/components/RejectTranslationModal/RejectTranslationModal.story.js
  server/zanata-frontend/src/app/editor/components/TransUnitTranslationPanel.js
  server/zanata-frontend/src/app/editor/components/TransUnitTranslationPanel.test.js
  server/zanata-frontend/src/package.json
  server/zanata-frontend/src/yarn.lock
Labels: Ignore CodeCov, Reviewed, Verified

#935 fix(test): convert concurrentedit tests to Kotlin
  server/functional-test/src/test/java/org/zanata/feature/concurrentedit/ConcurrentAccessTest.java
  server/functional-test/src/test/java/org/zanata/feature/concurrentedit/ConcurrentAccessTest.kt
  server/functional-test/src/test/java/org/zanata/feature/concurrentedit/ConcurrentEditTest.java
  server/functional-test/src/test/java/org/zanata/feature/concurrentedit/ConcurrentEditTest.kt
  server/functional-test/src/test/java/org/zanata/feature/concurrentedit/ConcurrentEditTestSuite.java
  server/functional-test/src/test/java/org/zanata/feature/concurrentedit/ConcurrentEditTestSuite.kt
Labels: No QA (1st vote), No QA (2nd vote), Reviewed

#927 react: server config
  .editorconfig
  server/functional-test/src/main/java/org/zanata/page/administration/ServerConfigurationPage.java
  server/functional-test/src/test/java/org/zanata/feature/administration/ServerSettingsTest.java
  server/functional-test/src/test/java/org/zanata/feature/endtoend/AdminEndToEndTest.java
  server/functional-test/src/test/java/org/zanata/feature/misc/RateLimitRestAndUITest.java
  server/services/src/main/java/org/zanata/action/ServerConfigurationBean.java
  server/services/src/main/java/org/zanata/rest/admin/ServerSettingsService.java
  server/services/src/main/java/org/zanata/servlet/UrlRewriteConfig.java
  server/services/src/test/java/org/zanata/rest/admin/ServerSettingsServiceTest.java
  server/zanata-frontend/src/app/actions/admin-actions.ts
  server/zanata-frontend/src/app/containers/Admin/ServerSettings.tsx
  server/zanata-frontend/src/app/containers/Admin/index.js
  server/zanata-frontend/src/app/containers/Root.js
  server/zanata-frontend/src/app/reducers/admin-reducer.js
  server/zanata-frontend/src/app/reducers/admin-reducer.test.js
  server/zanata-frontend/src/app/styles/antd.less
  server/zanata-frontend/src/index.html
  server/zanata-war/src/main/webapp/account/register.xhtml
  server/zanata-war/src/main/webapp/admin/home.xhtml
  server/zanata-war/src/main/webapp/admin/server_configuration.xhtml
Labels: Reviewed, Verified

#943 feat(ZNTA-2078): translation permalinks in alpha editor
  server/zanata-frontend/src/app/editor/components/TransUnitSourceHeader.js
  server/zanata-frontend/src/app/editor/components/TransUnitTranslationHeader.js
  server/zanata-frontend/src/app/editor/middlewares/new-context-fetch.js
  server/zanata-frontend/src/messages/ja.json
Labels: Reviewed, Verified

#924 feat(ZNTA-2635): editor validators error behavior
  server/zanata-frontend/src/.storybook-editor/__snapshots__/storyshots-editor.test.js.snap
  server/zanata-frontend/src/app/editor/actions/key-shortcuts-actions.js
  server/zanata-frontend/src/app/editor/actions/phrases-action-types.js
  server/zanata-frontend/src/app/editor/actions/phrases-actions.js
  server/zanata-frontend/src/app/editor/components/TransUnitTranslationFooter.js
  server/zanata-frontend/src/app/editor/components/TransUnitTranslationHeader.js
  server/zanata-frontend/src/app/editor/components/TransUnitTranslationPanel.js
  server/zanata-frontend/src/app/editor/components/TransUnitTranslationPanel.test.js
  server/zanata-frontend/src/app/editor/components/Validation/Validation.test.js
  server/zanata-frontend/src/app/editor/components/Validation/index.tsx
  server/zanata-frontend/src/app/editor/components/ValidationErrorsModal/index.tsx
  server/zanata-frontend/src/app/editor/containers/TranslationInfoPanel/index.js
  server/zanata-frontend/src/app/editor/reducers/phrase-reducer/index.js
  server/zanata-frontend/src/app/editor/utils/phrase-util.ts
  server/zanata-frontend/src/app/editor/utils/phrase.ts
  server/zanata-frontend/src/app/editor/utils/status-util.ts
  server/zanata-frontend/src/app/editor/watchers/phrase-detail.js
  server/zanata-frontend/src/app/validators/AbstractValidationAction.ts
  server/zanata-frontend/src/app/validators/ValidationMessages.ts
  server/zanata-frontend/src/app/validators/impl/JavaVariablesValidation.ts
  server/zanata-frontend/src/app/validators/impl/PrintfVariablesValidation.ts
  server/zanata-frontend/src/app/validators/impl/PrintfXSIExtensionValidation.test.js
  server/zanata-frontend/src/app/validators/impl/XmlEntityValidation.test.js
Labels: Reviewed, Verified

#945 Add incomplete types for Redux state
  server/zanata-frontend/src/.eslintrc
  server/zanata-frontend/src/app/actions/common-actions.ts
  server/zanata-frontend/src/app/actions/glossary-actions.js
  server/zanata-frontend/src/app/actions/tmx-actions.js
  server/zanata-frontend/src/app/reducers/admin-reducer.js
  server/zanata-frontend/src/app/reducers/common-reducer.js
  server/zanata-frontend/src/app/reducers/explore-reducer.js
  server/zanata-frontend/src/app/reducers/glossary-reducer.js
  server/zanata-frontend/src/app/reducers/languages-reducer.js
  server/zanata-frontend/src/app/reducers/profile-reducer.js
  server/zanata-frontend/src/app/reducers/state.ts
  server/zanata-frontend/src/app/reducers/tmx-reducer.js
  server/zanata-frontend/src/app/utils/DateHelper.ts
  server/zanata-frontend/src/app/utils/DeepReadonly.d.ts
  server/zanata-frontend/src/app/utils/prop-types-util.ts
  server/zanata-frontend/src/tslint.json
Labels: Ignore CodeCov, No QA (1st vote), No QA (2nd vote)

#947 Add types for editor state
  server/zanata-frontend/src/app/components/Icon/index.tsx
  server/zanata-frontend/src/app/editor/components/ActivitySelectList/index.js
  server/zanata-frontend/src/app/editor/components/GlossaryTermModal/index.ts
  server/zanata-frontend/src/app/editor/containers/ActivityTab.tsx
  server/zanata-frontend/src/app/editor/reducers/activity-reducer.js
  server/zanata-frontend/src/app/editor/reducers/context-reducer.test.js
  server/zanata-frontend/src/app/editor/reducers/context-reducer.ts
  server/zanata-frontend/src/app/editor/reducers/dropdown-reducer.ts
  server/zanata-frontend/src/app/editor/reducers/glossary-reducer.js
  server/zanata-frontend/src/app/editor/reducers/header-data-reducer.js
  server/zanata-frontend/src/app/editor/reducers/phrase-reducer/filter-status-reducer.js
  server/zanata-frontend/src/app/editor/reducers/phrase-reducer/index.js
  server/zanata-frontend/src/app/editor/reducers/phrase-reducer/phrase-filter-reducer.js
  server/zanata-frontend/src/app/editor/reducers/review-trans-reducer.js
  server/zanata-frontend/src/app/editor/reducers/settings-reducer.js
  server/zanata-frontend/src/app/editor/reducers/state.ts
  server/zanata-frontend/src/app/editor/reducers/suggestions-reducer.js
  server/zanata-frontend/src/app/editor/reducers/ui-reducer.js
  server/zanata-frontend/src/app/editor/utils/activity-util.ts
  server/zanata-frontend/src/app/utils/prop-types-util.ts
  server/zanata-frontend/src/package.json
  server/zanata-frontend/src/yarn.lock
Labels: No QA (1st vote), No QA (2nd vote), Reviewed

#911 feat(ZNTA-2300): editor concurrent save resolution
  server/services/src/main/java/org/zanata/rest/editor/dto/TranslationData.java
  server/services/src/main/java/org/zanata/rest/editor/service/TranslationService.java
  server/services/src/test/java/org/zanata/rest/editor/dto/TranslationDataTest.java
  server/zanata-frontend/src/app/containers/Admin/Review.js
  server/zanata-frontend/src/app/containers/Admin/ServerSettings.tsx
  server/zanata-frontend/src/app/containers/Languages/index.js
  server/zanata-frontend/src/app/containers/UserProfile/index.jsx
  server/zanata-frontend/src/app/editor/actions/phrases-action-types.js
  server/zanata-frontend/src/app/editor/actions/phrases-actions.js
  server/zanata-frontend/src/app/editor/components/ConcurrentModal/Concurrent.story.js
  server/zanata-frontend/src/app/editor/components/ConcurrentModal/index.js
  server/zanata-frontend/src/app/editor/components/ConcurrentModal/index.tsx
  server/zanata-frontend/src/app/editor/components/TransUnitTranslationFooter.js
  server/zanata-frontend/src/app/editor/components/TransUnitTranslationPanel.js
  server/zanata-frontend/src/app/editor/components/components.story.js
  server/zanata-frontend/src/app/editor/containers/MainContent.js
  server/zanata-frontend/src/app/editor/containers/TranslationInfoPanel/index.js
  server/zanata-frontend/src/app/editor/reducers/phrase-reducer/index.js
  server/zanata-frontend/src/app/editor/reducers/phrase-reducer/phrase-reducer.test.js
  server/zanata-frontend/src/app/editor/reducers/review-trans-reducer.js
  server/zanata-frontend/src/app/editor/reducers/review-trans-reducer.test.js
  server/zanata-frontend/src/app/reducers/admin-reducer.js
  server/zanata-frontend/src/app/reducers/admin-reducer.test.js
  server/zanata-frontend/src/app/reducers/glossary-reducer.js
  server/zanata-frontend/src/app/reducers/languages-reducer.js
  server/zanata-frontend/src/app/reducers/profile-reducer.js
  server/zanata-frontend/src/app/reducers/version-reducer.js
Labels: Ignore CodeCov, Reviewed, Verified

#952 style(ZNTA-2537) update storybooks and tests
  server/zanata-frontend/src/.storybook-frontend/__snapshots__/storyshots-frontend.test.js.snap
  server/zanata-frontend/src/app/components/Button/Button.story.js
  server/zanata-frontend/src/app/components/LockIcon/LockIcon.test.js
  server/zanata-frontend/src/app/components/LockIcon/index.tsx
  server/zanata-frontend/src/app/components/components.story.js
  server/zanata-frontend/src/app/styles/antd.less
Labels: No QA (1st vote), No QA (2nd vote), Reviewed

#944 feat(ZNTA-2504) Finish MT Merge UI
  .editorconfig
  server/services/src/main/resources/messages.properties
  server/zanata-frontend/src/.storybook-frontend/__snapshots__/storyshots-frontend.test.js.snap
  server/zanata-frontend/src/.storybook-frontend/storyshots-frontend.test.js
  server/zanata-frontend/src/app/actions/common-actions.ts
  server/zanata-frontend/src/app/actions/version-action-types.js
  server/zanata-frontend/src/app/actions/version-actions.js
  server/zanata-frontend/src/app/components/MTMerge/MTMerge.story.tsx
  server/zanata-frontend/src/app/components/MTMerge/MTMergeModal.tsx
  server/zanata-frontend/src/app/components/MTMerge/MTMergeOptions.tsx
  server/zanata-frontend/src/app/components/ProgressBar/CancellableProgressBar.test.js
  server/zanata-frontend/src/app/components/components.story.js
  server/zanata-frontend/src/app/containers/ProjectVersion/MTMerge.js
  server/zanata-frontend/src/app/containers/ProjectVersion/MTMergeContainer.ts
  server/zanata-frontend/src/app/containers/ProjectVersion/TMMergeModal.js
  server/zanata-frontend/src/app/containers/ProjectVersion/index.js
  server/zanata-frontend/src/app/editor/containers/TranslationInfoPanel/index.js
  server/zanata-frontend/src/app/editor/utils/status-util.ts
  server/zanata-frontend/src/app/jsf/index.js
  server/zanata-frontend/src/app/reducers/index.ts
  server/zanata-frontend/src/app/reducers/state.ts
  server/zanata-frontend/src/app/reducers/version-reducer.js
  server/zanata-frontend/src/app/reducers/version-reducer.test.js
  server/zanata-frontend/src/app/utils/EnumValueUtils.ts
  server/zanata-frontend/src/app/utils/TypeName.d.ts
  server/zanata-frontend/src/tsconfig.json
  server/zanata-frontend/src/webpack.config.js
  server/zanata-war/src/main/webapp/iteration/view.xhtml
Labels: Reviewed, Verified

#953 refactor(ZNTA-2529) change colour of suggestions heading in editor
  server/zanata-frontend/src/app/editor/containers/SuggestionsHeader.js
Labels: No QA (1st vote), No QA (2nd vote), Reviewed

#925 fix(ZNTA-2634): replace language property in translated TS
  server/services/src/main/java/org/zanata/adapter/OkapiFilterAdapter.java
  server/services/src/main/java/org/zanata/adapter/TSAdapter.java
  server/services/src/test/java/org/zanata/adapter/AbstractAdapterTest.java
  server/services/src/test/java/org/zanata/adapter/TSAdapterTest.java
  server/services/src/test/java/org/zanata/adapter/TSAdapterTest.kt
  server/services/src/test/resources/org/zanata/adapter/basicts.ts
  server/services/src/test/resources/org/zanata/adapter/test-ts-comment.ts
  server/services/src/test/resources/org/zanata/adapter/test-ts-invalid.ts
  server/services/src/test/resources/org/zanata/adapter/test-ts-multiplecontexts.ts
  server/services/src/test/resources/org/zanata/adapter/test-ts-plurals.ts
  server/services/src/test/resources/org/zanata/adapter/test-ts-translated.ts
  server/services/src/test/resources/org/zanata/adapter/test-ts-untranslated.ts
  server/zanata-model/src/main/java/org/zanata/util/OkapiUtil.java
Labels: Reviewed, Verified

#923 feat(ZNTA-2075) story for editor search and replace
  server/zanata-frontend/src/.storybook-editor/__snapshots__/storyshots-editor.test.js.snap
  server/zanata-frontend/src/.storybook-editor/storyshots-editor.test.js
  server/zanata-frontend/src/.storybook-frontend/__snapshots__/storyshots-frontend.test.js.snap
  server/zanata-frontend/src/.storybook-frontend/config.js
  server/zanata-frontend/src/app/editor/app.css
  server/zanata-frontend/src/app/editor/components/SearchReplace/SearchReplace.story.js
  server/zanata-frontend/src/app/editor/components/SearchReplace/index.css
  server/zanata-frontend/src/app/editor/components/SearchReplace/index.js
  server/zanata-frontend/src/app/editor/components/components.story.js
  server/zanata-frontend/src/app/editor/entrypoint/index.js
Labels: No QA (1st vote), No QA (2nd vote), Reviewed

#958 fix: concurrent modal type error
  server/zanata-frontend/src/app/editor/containers/MainContent.js
Labels: Reviewed, Verified

#959 Fix attribution for DEV mode MT
  server/services/src/main/java/org/zanata/service/impl/MachineTranslationServiceImpl.java
Labels: Reviewed, Verified

#956 feat(ZNTA-2664): Improve UI for MT merge
  server/services/src/main/resources/messages.properties
  server/zanata-frontend/src/.storybook-frontend/__snapshots__/storyshots-frontend.test.js.snap
  server/zanata-frontend/src/app/components/MTMerge/MTMergeModal.tsx
Labels: Ignore CodeCov, Reviewed, Verified

#961 fix(string): Successfuly fix a typo
  server/zanata-frontend/src/app/reducers/version-reducer.js
Labels: Ignore CodeCov, No QA (1st vote), No QA (2nd vote), Reviewed

#960 refactor: eliminate duplicate TranslationSourceType
  api/zanata-common-api/src/main/java/org/zanata/Common.gwt.xml
  api/zanata-common-api/src/main/java/org/zanata/rest/dto/TransUnitStatus.java
  api/zanata-common-api/src/main/java/org/zanata/rest/dto/TranslationSourceType.java
  api/zanata-common-api/src/main/java/org/zanata/rest/service/ProjectVersionResource.java
  api/zanata-common-api/src/test/java/org/zanata/rest/dto/TransUnitStatusTest.java
  server/gwt-editor/src/main/java/org/zanata/webtrans/client/ui/Editor.java
  server/gwt-editor/src/main/java/org/zanata/webtrans/client/ui/TransSourceIndicator.java
  server/gwt-editor/src/main/java/org/zanata/webtrans/client/view/TransMemoryView.java
  server/gwt-editor/src/test/java/org/zanata/webtrans/client/presenter/ComparingPairTest.java
  server/gwt-editor/src/test/java/org/zanata/webtrans/client/presenter/TranslationHistoryPresenterTest.java
  server/gwt-shared/src/main/java/org/zanata/webtrans/shared/model/TransHistoryItem.java
  server/gwt-shared/src/main/java/org/zanata/webtrans/shared/model/TransUnit.java
  server/gwt-shared/src/main/java/org/zanata/webtrans/shared/model/TranslationSourceType.java
  server/services/src/main/java/org/zanata/action/VersionHomeAction.java
  server/services/src/main/java/org/zanata/dao/DocumentDAO.java
  server/services/src/main/java/org/zanata/file/TranslationDocumentUpload.java
  server/services/src/main/java/org/zanata/rest/editor/dto/suggestion/TextFlowSuggestionDetail.java
  server/services/src/main/java/org/zanata/rest/editor/service/StatisticsService.java
  server/services/src/main/java/org/zanata/rest/editor/service/TranslationService.java
  server/services/src/main/java/org/zanata/rest/service/AsynchronousProcessResourceService.java
  server/services/src/main/java/org/zanata/rest/service/FileService.java
  server/services/src/main/java/org/zanata/rest/service/ProjectVersionService.java
  server/services/src/main/java/org/zanata/rest/service/TranslatedDocResourceService.java
  server/services/src/main/java/org/zanata/search/FilterConstraintToQuery.java
  server/services/src/main/java/org/zanata/service/TranslationService.java
  server/services/src/main/java/org/zanata/service/impl/CopyTransWorkFactory.java
  server/services/src/main/java/org/zanata/service/impl/CopyVersionServiceImpl.java
  server/services/src/main/java/org/zanata/service/impl/MachineTranslationServiceImpl.java
  server/services/src/main/java/org/zanata/service/impl/MergeTranslationsServiceImpl.java
  server/services/src/main/java/org/zanata/service/impl/TranslationMemoryServiceImpl.java
  server/services/src/main/java/org/zanata/service/impl/TranslationServiceImpl.java
  server/services/src/main/java/org/zanata/service/tm/merge/TransMemoryMergeServiceImpl.java
  server/services/src/main/java/org/zanata/webtrans/server/rpc/GetTransUnitsNavigationService.java
  server/services/src/main/java/org/zanata/webtrans/server/rpc/GetTranslationHistoryHandler.java
  server/services/src/main/java/org/zanata/webtrans/server/rpc/TransUnitTransformer.java
  server/services/src/test/java/org/zanata/dao/DocumentDAOTest.java
  server/services/src/test/java/org/zanata/dao/TextFlowTargetDAOTest.java
  server/services/src/test/java/org/zanata/file/TranslationDocumentUploadTest.java
  server/services/src/test/java/org/zanata/model/HTextFlowBuilder.java
  server/services/src/test/java/org/zanata/rest/editor/service/StatisticsServiceTest.java
  server/services/src/test/java/org/zanata/rest/service/FileServiceTest.java
  server/services/src/test/java/org/zanata/search/FilterConstraintToQueryJpaTest.java
  server/services/src/test/java/org/zanata/search/FilterConstraintToQueryTest.java
  server/services/src/test/java/org/zanata/service/impl/CopyTransServiceImplParameterizedTest.java
  server/services/src/test/java/org/zanata/service/impl/CopyVersionServiceImplTest.java
  server/services/src/test/java/org/zanata/service/impl/MergeTranslationsServiceImplTest.java
  server/services/src/test/java/org/zanata/service/impl/TranslationServiceImplJpaTest.java
  server/services/src/test/java/org/zanata/service/impl/TranslationServiceImplTest.java
  server/services/src/test/java/org/zanata/service/tm/merge/TransMemoryMergeServiceImplTest.java
  server/zanata-model/src/main/java/org/zanata/model/HTextFlowTarget.java
  server/zanata-model/src/main/java/org/zanata/model/HTextFlowTargetHistory.java
  server/zanata-model/src/main/java/org/zanata/model/type/TranslationSourceTypeType.java
  server/zanata-model/src/main/java/org/zanata/model/type/TranslationSourceTypeTypeDescriptor.java
  server/zanata-model/src/test/java/org/zanata/model/type/TranslationSourceTypeTest.java
Labels: No QA (1st vote), No QA (2nd vote), Reviewed

#964 fix(ZNTA-2669) use HTML attributes for MT in GWT editor
  server/gwt-editor/src/main/java/org/zanata/webtrans/client/presenter/TranslationHistoryPresenter.java
  server/gwt-editor/src/main/java/org/zanata/webtrans/client/ui/Editor.java
  server/gwt-editor/src/main/java/org/zanata/webtrans/client/ui/TextContentsDisplay.java
  server/gwt-editor/src/main/java/org/zanata/webtrans/client/ui/TransHistoryItemLine.java
  server/gwt-editor/src/main/java/org/zanata/webtrans/client/ui/TransSourceIndicator.java
  server/gwt-editor/src/main/java/org/zanata/webtrans/client/ui/TranslationHistoryDisplay.java
  server/gwt-editor/src/main/java/org/zanata/webtrans/client/view/TargetContentsView.java
  server/gwt-editor/src/main/java/org/zanata/webtrans/client/view/TransMemoryView.java
  server/gwt-editor/src/test/java/org/zanata/webtrans/client/presenter/TranslationHistoryPresenterTest.java
  server/zanata-frontend/src/app/editor/components/TransUnit/index.css
Labels: Reviewed, Verified

#854 fix(ZNTA-2581,ZNTA-1731): fix textflow id of uploaded JSON documents
  docs/release-notes.md
  server/pom.xml
  server/services/pom.xml
  server/services/src/main/java/org/zanata/action/VersionHomeAction.java
  server/services/src/main/java/org/zanata/adapter/FileFormatAdapter.kt
  server/services/src/main/java/org/zanata/adapter/GenericPropertiesAdapter.java
  server/services/src/main/java/org/zanata/adapter/GettextAdapter.java
  server/services/src/main/java/org/zanata/adapter/JsonAdapter.java
  server/services/src/main/java/org/zanata/adapter/JsonAdapter.kt
  server/services/src/main/java/org/zanata/adapter/OkapiFilterAdapter.java
  server/services/src/main/java/org/zanata/adapter/TSAdapter.java
  server/services/src/main/java/org/zanata/adapter/XliffAdapter.java
  server/services/src/main/resources/messages.properties
  server/services/src/test/java/org/zanata/adapter/JsonAdapterTest.java
  server/services/src/test/java/org/zanata/adapter/JsonAdapterTest.kt
  server/services/src/test/java/org/zanata/service/impl/TranslationFileServiceImplTest.java
  server/services/src/test/resources/org/zanata/adapter/basicjson.json
  server/services/src/test/resources/org/zanata/adapter/test-json-duplicatecontent.json
  server/services/src/test/resources/org/zanata/adapter/test-json-duplicateentries.json
  server/services/src/test/resources/org/zanata/adapter/test-json-duplicateids.json
  server/services/src/test/resources/org/zanata/adapter/test-json-untranslated.json
  server/zanata-war/src/main/webapp/WEB-INF/layout/version/languages-tab.xhtml
  server/zanata-war/src/main/webapp/WEB-INF/layout/version/upload_translation_modal.xhtml
Labels: Reviewed, Verified

#962 fix(ZNTA-2671): skip loop on failed attribution check
  server/services/src/main/java/org/zanata/service/impl/MachineTranslationServiceImpl.java
Labels: Ignore CodeCov, Reviewed, Verified

#966 fix: ensure transaction for attribution
  server/services/src/main/java/org/zanata/service/impl/MachineTranslationServiceImpl.java
Labels: Release, Reviewed, Verified

#971 fix(ZNTA-2680) fix height of project settings languages buttons
  server/zanata-frontend/src/app/styles/frontend-jsf.less
  server/zanata-war/src/main/webapp/WEB-INF/layout/project/settings-tab-languages.xhtml
Labels: Release, Reviewed, Verified

#972 fix(ZNTA-2676) colour for copytrans modal state buttons
  server/zanata-frontend/src/app/styles/frontend-jsf.less
Labels: Release, Reviewed, Verified

#968 fix(ZNTA-2679): React Editor status icon and disabled button styles
  server/zanata-frontend/src/app/editor/components/Button/index.css
  server/zanata-frontend/src/app/editor/components/TransUnit/index.css
Labels: Release, Reviewed, Verified

#949 chore(ZNTA-2652): Upgrade Webpack
  server/services/src/test/java/org/zanata/action/FrontendAssetsTest.kt
  server/zanata-frontend/pom.xml
  server/zanata-frontend/src/.babelrc
  server/zanata-frontend/src/.storybook-editor/__snapshots__/storyshots-editor.test.js.snap
  server/zanata-frontend/src/.storybook-editor/webpack.config.js
  server/zanata-frontend/src/app/components/EditableText/EditableText.story.js
  server/zanata-frontend/src/app/components/Icon/Icon.story.js
  server/zanata-frontend/src/app/components/Link/Link.story.js
  server/zanata-frontend/src/app/components/LoaderText/LoaderText.story.js
  server/zanata-frontend/src/app/components/ProgressBar/ProgressBar.story.js
  server/zanata-frontend/src/app/components/RejectionsForm/RejectionsForm.story.js
  server/zanata-frontend/src/app/components/Sidebar/Sidebar.story.js
  server/zanata-frontend/src/app/components/TextInput/TextInput.story.js
  server/zanata-frontend/src/app/components/TriCheckbox/TriCheckbox.story.js
  server/zanata-frontend/src/app/components/foundation.story.js
  server/zanata-frontend/src/app/containers/ProjectVersion/AboutPage.js
  server/zanata-frontend/src/app/containers/ProjectVersion/DocumentsPage.js
  server/zanata-frontend/src/app/containers/ProjectVersion/GroupsPage.js
  server/zanata-frontend/src/app/containers/ProjectVersion/LanguagesPage.js
  server/zanata-frontend/src/app/containers/ProjectVersion/PeoplePage.js
  server/zanata-frontend/src/app/editor/components/IconButton/IconButton.story.js
  server/zanata-frontend/src/app/editor/components/ProgressBar/ProgressBar.story.js
  server/zanata-frontend/src/package.json
  server/zanata-frontend/src/scripts/build.js
  server/zanata-frontend/src/scripts/dev-server.js
  server/zanata-frontend/src/webpack.common.js
  server/zanata-frontend/src/webpack.config.js
  server/zanata-frontend/src/webpack.dev.js
  server/zanata-frontend/src/webpack.prod.js
  server/zanata-frontend/src/webpack.story.js
  server/zanata-frontend/src/yarn.lock
Labels: Release, Reviewed, Verified

#974 fix: refresh project list on language selection
  server/zanata-war/src/main/webapp/iteration/view.xhtml
  server/zanata-war/src/main/webapp/version-group/version_group.xhtml
Labels: Release, Reviewed, Verified

#976 fix(ZNTA-2681): language page sort and search
  server/zanata-frontend/src/app/containers/Languages/index.js
Labels: Release, Reviewed, Verified

#772 Add auditjs
  Jenkinsfile
  server/zanata-frontend/src/.gitignore
  server/zanata-frontend/src/auditjs-whitelist.json
  server/zanata-frontend/src/package.json
  server/zanata-frontend/src/yarn.lock
Labels: Ignore CodeCov, No QA (1st vote), No QA (2nd vote), Release, Reviewed

#978 fix(ZNTA-2685) minor editor css fixes
  server/zanata-frontend/src/.storybook-editor/__snapshots__/storyshots-editor.test.js.snap
  server/zanata-frontend/src/app/editor/components/ActivitySelectList/index.js
  server/zanata-frontend/src/app/editor/containers/Sidebar/index.css
Labels: Release, Reviewed, Verified

#975 fix(ZNTA-2677) explore page pagination next button fixed
  server/zanata-frontend/src/app/containers/Explore/TeaserListHeader.jsx
  server/zanata-frontend/src/app/styles/antd.less
Labels: Release, Reviewed, Verified

#969 fix(ZNTA-2674)(ZNTA-2675) ui fixes to project version settings
  server/zanata-frontend/src/app/styles/frontend-jsf.less
  server/zanata-war/src/main/webapp/WEB-INF/layout/version/edit_form.xhtml
  server/zanata-war/src/main/webapp/WEB-INF/layout/version/settings-tab-languages.xhtml
  server/zanata-war/src/main/webapp/WEB-INF/layout/version/settings-tab.xhtml
Labels: Release, Reviewed, Verified

#973 chore(ZNTA-2478): enable ossindex audit to fail build
  client/pom.xml
  client/zanata-maven-plugin/pom.xml
  parent/pom.xml
  server/pom.xml
Labels: Ignore CodeCov, No QA (1st vote), No QA (2nd vote), Release, Reviewed

#979 fix(ZNTA-2682): languages pagination
  server/zanata-frontend/src/app/containers/Languages/index.js
  server/zanata-frontend/src/app/styles/antd.less
Labels: Release, Reviewed, Verified

#984 fix(ZNTA-2695): terms url
  server/zanata-war/src/main/webapp/account/create_user.xhtml
  server/zanata-war/src/main/webapp/account/register.xhtml
Labels: Release, Reviewed, Verified

#988 fix(ZNTA-2703) hover colour for link panels on admin homepage
  server/zanata-frontend/src/app/containers/Admin/index.less
Labels: No QA (1st vote), No QA (2nd vote), Release, Reviewed

#987 fix(ZNTA-2705) reduce spacing between explore page search and content
  server/zanata-frontend/src/app/containers/Explore/index.js
Labels: No QA (1st vote), No QA (2nd vote), Release, Reviewed

#985 fix: language search
  server/zanata-frontend/src/app/containers/Languages/index.js
Labels: On QA spathare, Release, Reviewed, Verified

#983 fix(ZNTA-2683): state filter on profile page
  server/zanata-frontend/src/app/containers/UserProfile/ContentStateFilter.jsx
  server/zanata-frontend/src/app/containers/UserProfile/index.less
Labels: Release, Reviewed, Verified

#994 fix(ZNTA-2704) alignment of save and delete buttons on review criteria admin page
  server/zanata-frontend/src/app/components/RejectionsForm/index.js
Labels: Ignore CodeCov, No QA (1st vote), No QA (2nd vote), Release, Reviewed

#996 fix(ZNTA-2707) use zanata colours for antd notification icons
  server/zanata-frontend/src/app/styles/antd.less
Labels: No QA (1st vote), No QA (2nd vote), Release, Reviewed

#995 fix(ZNTA-2706) alignment of react editor header nav arrows
  server/zanata-frontend/src/app/editor/containers/NavHeader.js
  server/zanata-frontend/src/app/editor/containers/Root/index.css
Labels: No QA (1st vote), No QA (2nd vote), Release, Reviewed

#990 fix(ZNTA-2701) hover, focus, active border colour for language pagination
  server/zanata-frontend/src/app/styles/antd.less
Labels: No QA (1st vote), No QA (2nd vote), Release, Reviewed

#993 fix(ZNTA-2702) add margin between MT Merge modal alerts
  server/zanata-frontend/src/.storybook-frontend/__snapshots__/storyshots-frontend.test.js.snap
  server/zanata-frontend/src/app/components/MTMerge/MTMergeOptions.tsx
Labels: No QA (1st vote), No QA (2nd vote), Release, Reviewed

#989 fix(ZNTA-2699) fix positioning of project glossary title
  server/zanata-frontend/src/app/containers/Glossary/ViewHeader.js
  server/zanata-frontend/src/app/containers/Glossary/index.less
Labels: Ignore CodeCov, No QA (1st vote), No QA (2nd vote), Release, Reviewed

#992 fix(ZNTA-2698) vertically align modal footer content
  server/zanata-frontend/src/app/styles/frontend-jsf.less
Labels: Ignore CodeCov, No QA (1st vote), No QA (2nd vote), Release, Reviewed

#997 fix(ZNTA-2708): specify duration for mtmerge process status notifications
  server/zanata-frontend/src/app/reducers/version-reducer.js
Labels: Release, Reviewed, Verified

#991 fix(ZNTA-2697) remove extra spacing from dashboard lists
  server/zanata-frontend/src/app/styles/frontend-jsf.less
  server/zanata-war/src/main/webapp/WEB-INF/layout/dashboard/projects.xhtml
Labels: Ignore CodeCov, On QA, On QA djansen, Release, Reviewed

#998 chore: update to Maven 3.5.4
  .mvn/wrapper/maven-wrapper.properties
Labels: No QA (1st vote), No QA (2nd vote), Reviewed

#999 Change node/yarn version properties
  server/zanata-frontend/pom.xml
Labels: No QA (1st vote), No QA (2nd vote), Reviewed

#1001 fix(ZNTA-2711)(ZNTA-2714) alignment of admin TM list items and editor pagination
  server/functional-test/src/main/java/org/zanata/page/administration/ManageUserPage.java
  server/zanata-frontend/src/app/editor/components/Pager/Pager.test.tsx
  server/zanata-frontend/src/app/editor/components/Pager/index.js
  server/zanata-frontend/src/app/editor/containers/ControlsHeader.js
  server/zanata-frontend/src/app/styles/frontend-jsf.less
Labels: Release, Reviewed, Verified

#1002 fix(ZNTA-2712) admin breadcrumbs
  server/zanata-frontend/src/app/styles/antd.less
  server/zanata-frontend/src/app/styles/frontend-jsf.less
  server/zanata-war/src/main/webapp/admin/cachestats.xhtml
  server/zanata-war/src/main/webapp/admin/create_user.xhtml
  server/zanata-war/src/main/webapp/admin/processmanager.xhtml
  server/zanata-war/src/main/webapp/admin/roledetail.xhtml
  server/zanata-war/src/main/webapp/admin/rolemanager.xhtml
  server/zanata-war/src/main/webapp/admin/roleruledetails.xhtml
  server/zanata-war/src/main/webapp/admin/rolerules.xhtml
  server/zanata-war/src/main/webapp/admin/search.xhtml
  server/zanata-war/src/main/webapp/admin/stats.xhtml
  server/zanata-war/src/main/webapp/admin/userdetail.xhtml
  server/zanata-war/src/main/webapp/admin/usermanager.xhtml
  server/zanata-war/src/main/webapp/tm/create.xhtml
  server/zanata-war/src/main/webapp/tm/home.xhtml
Labels: Release, Reviewed, Verified

#1003 feat(ZNTA-2716): Implement Editor UI Locale Select
  server/zanata-frontend/src/.storybook-editor/__snapshots__/storyshots-editor.test.js.snap
  server/zanata-frontend/src/app/editor/api/index.js
  server/zanata-frontend/src/app/editor/components/ActivitySelectList/index.js
  server/zanata-frontend/src/app/editor/components/CommentBox/index.tsx
  server/zanata-frontend/src/app/editor/components/EditorSearchInput/EditorSearchInput.test.js
  server/zanata-frontend/src/app/editor/components/EditorSearchInput/index.js
  server/zanata-frontend/src/app/editor/components/ToggleSwitch/index.js
  server/zanata-frontend/src/app/editor/components/UiLanguageDropdown/UiLanguageDropdown.test.js
  server/zanata-frontend/src/app/editor/components/UiLanguageDropdown/index.js
  server/zanata-frontend/src/app/editor/containers/NavHeader.js
  server/zanata-frontend/src/app/editor/containers/Root/ConnectedIntlProvider.js
  server/zanata-frontend/src/app/editor/containers/Root/index.js
  server/zanata-frontend/src/app/editor/containers/SettingsPanel.js
  server/zanata-frontend/src/app/editor/containers/SuggestionsHeader.js
  server/zanata-frontend/src/app/editor/entrypoint/index.js
  server/zanata-frontend/src/app/editor/reducers/header-data-reducer.js
  server/zanata-frontend/src/app/editor/reducers/header-data-reducer.test.js
  server/zanata-frontend/src/app/editor/reducers/state.ts
  server/zanata-frontend/src/messages/de.json
  server/zanata-frontend/src/messages/fr.json
  server/zanata-frontend/src/messages/index.ts
  server/zanata-frontend/src/messages/ja.json
  server/zanata-frontend/src/messages/ko.json
  server/zanata-frontend/src/messages/ru.json
  server/zanata-frontend/src/messages/zu.json
Labels: Reviewed, Verified

#1007 fix(ZNTA-2723) linting errors in storybooks
  server/zanata-frontend/src/app/editor/components/SearchReplace/SearchReplace.story.js
  server/zanata-frontend/src/app/editor/components/SearchReplace/index.js
  server/zanata-frontend/src/scripts/generateIconList.js
Labels: No QA (1st vote), No QA (2nd vote), Reviewed

#1008 docs: MT merge
  docs/images/mt-merge-process.png
  docs/images/version-more-action-menu.png
  docs/images/version-mt-dialog.png
  docs/images/version-mt-merge-language.png
  docs/user-guide/system-admin/configuration/installation.md
  docs/user-guide/versions/version-mt-merge.md
  mkdocs.yml
  server/zanata-frontend/src/.storybook-frontend/__snapshots__/storyshots-frontend.test.js.snap
  server/zanata-frontend/src/app/components/MTMerge/MTMergeOptions.tsx
Labels: No QA (1st vote), No QA (2nd vote), Reviewed
